{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-forge",
    "version": "0.8.4-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.4-dust.0.jar",
          "url": "minecraft-codev-forge-0.8.4-dust.0.jar",
          "size": 307467,
          "sha512": "902e30413ec2d29bab18acb9ad77a6e82cf0560d1f0d47463b0d411c7a98bf7af7be839bc2e5822d989ae5496b487a73227bd978e0b5050f24724e20d9c79dcc",
          "sha256": "84f76cfa5d129c4f47430dcdadbce5def2ab814d9c25c7b683f99e4cb4b7d830",
          "sha1": "1a4cdd386e2ca6f3c231517771ba990055e2cc13",
          "md5": "46d9ea3fa7ce4ce60421caaecad205eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core-serialization",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-cli",
          "version": {
            "requires": "13.0.3"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.1-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.8-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.4-dust.0.jar",
          "url": "minecraft-codev-forge-0.8.4-dust.0.jar",
          "size": 307467,
          "sha512": "902e30413ec2d29bab18acb9ad77a6e82cf0560d1f0d47463b0d411c7a98bf7af7be839bc2e5822d989ae5496b487a73227bd978e0b5050f24724e20d9c79dcc",
          "sha256": "84f76cfa5d129c4f47430dcdadbce5def2ab814d9c25c7b683f99e4cb4b7d830",
          "sha1": "1a4cdd386e2ca6f3c231517771ba990055e2cc13",
          "md5": "46d9ea3fa7ce4ce60421caaecad205eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.4-dust.0-sources.jar",
          "url": "minecraft-codev-forge-0.8.4-dust.0-sources.jar",
          "size": 36822,
          "sha512": "4e0cbbf6a85c9e1fb3dd33aa83057ea45aa5cdfd91f355d50baefbca7cf6b10ad29f245bd4e7a7e89331e105f87911645771ea4b0d10d93a798c7e8f79b30337",
          "sha256": "a564ab4d7201e7cf2f94885bee269751761f24db920dca7d5145009e0d59ecf3",
          "sha1": "fcb698b4d8c8c6eb25dee576ad9247022d7ab2b7",
          "md5": "fe91f2de08a7c918c7b496e7762be0e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.4-dust.0-javadoc.jar",
          "url": "minecraft-codev-forge-0.8.4-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
