{
  "formatVersion": "1.1",
  "component": {
    "group": "settingdust.preloading_tricks",
    "module": "PreloadingTricks",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-3.4.0.jar",
          "url": "PreloadingTricks-3.4.0.jar",
          "size": 1573632,
          "sha512": "279784910de64092102b0351cd51fd532a12bdf93dafb69b76a9c418649a6369845c116e14bb07105cd161e8259664eb296ed406573dc5cc2030df82c2576e4b",
          "sha256": "51b8869deac55d1e48ff7bee970ab2f0cbaacc4de0049490a495b7478efd10cb",
          "sha1": "c4570445140df43682cb025aaf4574b4a91b2cad",
          "md5": "967a7ee1ff2168992e281b4c222e4606"
        }
      ]
    },
    {
      "name": "forgeServiceApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.4.0-forge-service.jar",
          "url": "PreloadingTricks-3.4.0-forge-service.jar",
          "size": 936759,
          "sha512": "ca14453059f4e5bcdfd93ffc9242ee2e24fa51af822084f14cd4f9dd292d1b22ab2ef3a5ab536cefbac6cd749e51c4d06292f889b37f658b1b5b0e1a8c55db5d",
          "sha256": "41d5c902fb6b790e3606cd4af52bb11a77ef292e9afb89dd9e3093de4320e770",
          "sha1": "ebc4f23691d88e6b61bdf4f18391e0b820ecba53",
          "md5": "a7860c2bc42535d29e49f23c8ae36335"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "3.4.0"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.4.0"
        }
      ]
    },
    {
      "name": "forgeServiceRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.4.0-forge-service.jar",
          "url": "PreloadingTricks-3.4.0-forge-service.jar",
          "size": 936759,
          "sha512": "ca14453059f4e5bcdfd93ffc9242ee2e24fa51af822084f14cd4f9dd292d1b22ab2ef3a5ab536cefbac6cd749e51c4d06292f889b37f658b1b5b0e1a8c55db5d",
          "sha256": "41d5c902fb6b790e3606cd4af52bb11a77ef292e9afb89dd9e3093de4320e770",
          "sha1": "ebc4f23691d88e6b61bdf4f18391e0b820ecba53",
          "md5": "a7860c2bc42535d29e49f23c8ae36335"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "3.4.0"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.4.0"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherLegacyApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.6",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.20.6",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.4.0-neoforge-modlauncher-legacy.jar",
          "url": "PreloadingTricks-3.4.0-neoforge-modlauncher-legacy.jar",
          "size": 96118,
          "sha512": "63f6317569d352d173e3be87902302781138c7d0e454938addc9997ac4a45e92919d9ff768b32c33479fd08f0bd5121aec526da1a434bc32737f3385ba65f673",
          "sha256": "40b53df4e9abb3f63d2f1f9ef25679fff38bab6f750d2520b5226e19032ecb6c",
          "sha1": "0466dc566f79a6d59a89f80525b10f44e1deb967",
          "md5": "42ef97a7fe1af59529620897d393ece6"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher-legacy",
          "version": "3.4.0"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.4.0"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherLegacyRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.6",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.20.6",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.4.0-neoforge-modlauncher-legacy.jar",
          "url": "PreloadingTricks-3.4.0-neoforge-modlauncher-legacy.jar",
          "size": 96118,
          "sha512": "63f6317569d352d173e3be87902302781138c7d0e454938addc9997ac4a45e92919d9ff768b32c33479fd08f0bd5121aec526da1a434bc32737f3385ba65f673",
          "sha256": "40b53df4e9abb3f63d2f1f9ef25679fff38bab6f750d2520b5226e19032ecb6c",
          "sha1": "0466dc566f79a6d59a89f80525b10f44e1deb967",
          "md5": "42ef97a7fe1af59529620897d393ece6"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher-legacy",
          "version": "3.4.0"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.4.0"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.4.0-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.4.0-neoforge-modlauncher.jar",
          "size": 946312,
          "sha512": "e6089a1c4ef48da7f4e5411af6eae8763682cab0fc1cc6271479231480a657e6ab117e9a841ec643bac067e4997a5f63dbffeeff4b37d5a3096a764c9ce34867",
          "sha256": "e05b26386e616ee89f12fda291aaf58a549c47b02f1b2b37cd8cb39c99fb7578",
          "sha1": "b7bea883db26e8bea3bcb33bf98ed09d5ff0e6f3",
          "md5": "159961798ac7daea411c5bef006ba170"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "3.4.0"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.4.0"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.4.0-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.4.0-neoforge-modlauncher.jar",
          "size": 946312,
          "sha512": "e6089a1c4ef48da7f4e5411af6eae8763682cab0fc1cc6271479231480a657e6ab117e9a841ec643bac067e4997a5f63dbffeeff4b37d5a3096a764c9ce34867",
          "sha256": "e05b26386e616ee89f12fda291aaf58a549c47b02f1b2b37cd8cb39c99fb7578",
          "sha1": "b7bea883db26e8bea3bcb33bf98ed09d5ff0e6f3",
          "md5": "159961798ac7daea411c5bef006ba170"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "3.4.0"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.4.0"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.4.0-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.4.0-neoforge-fancy-mod-loader.jar",
          "size": 63057,
          "sha512": "f9e83dcb2723dcc0b767fc6907494fa1f24eb0c4cb4b57d3dde3e5af0d2a8a5bbe05adc2cd5820407b78f85713b0cf315a0d698143910b531f4ba7879991b956",
          "sha256": "65e0f4b35cd6ad0a1f3cb0cf84abc4b3e5c901e2a961b4845decb3465b973d5b",
          "sha1": "404af34716b9869f80bcdf6e90562915341e2689",
          "md5": "33ceb23a942e4aba4ef8b101974931cc"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.4.0"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "3.4.0"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.4-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.4.0-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.4.0-neoforge-fancy-mod-loader.jar",
          "size": 63057,
          "sha512": "f9e83dcb2723dcc0b767fc6907494fa1f24eb0c4cb4b57d3dde3e5af0d2a8a5bbe05adc2cd5820407b78f85713b0cf315a0d698143910b531f4ba7879991b956",
          "sha256": "65e0f4b35cd6ad0a1f3cb0cf84abc4b3e5c901e2a961b4845decb3465b973d5b",
          "sha1": "404af34716b9869f80bcdf6e90562915341e2689",
          "md5": "33ceb23a942e4aba4ef8b101974931cc"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.4.0"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "3.4.0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
