{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "kmp-actual-stubs-compiler-plugin",
    "version": "0.1.2-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-actual-stubs-compiler-plugin-0.1.2-dust.0.jar",
          "url": "kmp-actual-stubs-compiler-plugin-0.1.2-dust.0.jar",
          "size": 26793,
          "sha512": "5ad4a4e653bcc039a9dbb4610386092e17193ac15942f954624cb44ed764ef4128a86110dc3775a4b2641f70c61a350a5361cca3be2d8749dd5ff0749e9e71f0",
          "sha256": "3b57639617634e08659356d2d23d29c06be03c45b7f19eb43ebe974b230f374e",
          "sha1": "f045ec9342b7f481577113a5b73948be15d5fbc9",
          "md5": "4523d9adb2690e5fb14e497c6b8dc60d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-actual-stubs-compiler-plugin-0.1.2-dust.0.jar",
          "url": "kmp-actual-stubs-compiler-plugin-0.1.2-dust.0.jar",
          "size": 26793,
          "sha512": "5ad4a4e653bcc039a9dbb4610386092e17193ac15942f954624cb44ed764ef4128a86110dc3775a4b2641f70c61a350a5361cca3be2d8749dd5ff0749e9e71f0",
          "sha256": "3b57639617634e08659356d2d23d29c06be03c45b7f19eb43ebe974b230f374e",
          "sha1": "f045ec9342b7f481577113a5b73948be15d5fbc9",
          "md5": "4523d9adb2690e5fb14e497c6b8dc60d"
        }
      ]
    }
  ]
}
