{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "jvm-virtual-source-sets",
    "version": "1.3.6-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jvm-virtual-source-sets-1.3.6-dust.0.jar",
          "url": "jvm-virtual-source-sets-1.3.6-dust.0.jar",
          "size": 51756,
          "sha512": "f3e016ae0352754c75d7c370c7a119ef9d694b68f9a2dc80fe6ca8c61b68d68531fb41f9062e1308d97ef478ffa5c4fe9b7eb670c1edbefac87c010fbd7c14e6",
          "sha256": "5ac4a12cda9b00f85101b6d15bd842c16dd9ef7133c1a98e4e98ca24fb8b374e",
          "sha1": "6f28d241ad591f9511afaafc5cda5b9a57d6b4bd",
          "md5": "6fc5470ec58f523f810c79accb1b261a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jvm-virtual-source-sets-1.3.6-dust.0.jar",
          "url": "jvm-virtual-source-sets-1.3.6-dust.0.jar",
          "size": 51756,
          "sha512": "f3e016ae0352754c75d7c370c7a119ef9d694b68f9a2dc80fe6ca8c61b68d68531fb41f9062e1308d97ef478ffa5c4fe9b7eb670c1edbefac87c010fbd7c14e6",
          "sha256": "5ac4a12cda9b00f85101b6d15bd842c16dd9ef7133c1a98e4e98ca24fb8b374e",
          "sha1": "6f28d241ad591f9511afaafc5cda5b9a57d6b4bd",
          "md5": "6fc5470ec58f523f810c79accb1b261a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jvm-virtual-source-sets-1.3.6-dust.0-sources.jar",
          "url": "jvm-virtual-source-sets-1.3.6-dust.0-sources.jar",
          "size": 4232,
          "sha512": "50c4902d8e87e20fcfa81e6de423bef8f1950cac91cd0ed089e4155699c30d56a2cda35010bebd3e1adcd39f48780dc0505b314349d931da73fa204df3790f38",
          "sha256": "df5639398b3fbd10e94f2d7fbc85daf0dd814683253b70e0e339b93bd3d6c7ae",
          "sha1": "8428b3bde95d3fa4cf4e5eac37e4577bad7821de",
          "md5": "15fd30cb3ff567d41a34cd99e60bebd3"
        }
      ]
    }
  ]
}
