{
  "formatVersion": "1.1",
  "component": {
    "group": "settingdust.preloading_tricks",
    "module": "PreloadingTricks",
    "version": "3.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-3.5.14.jar",
          "url": "PreloadingTricks-3.5.14.jar",
          "size": 1892165,
          "sha512": "89da391dd5091d9a6ceb88816f47c1388a0815bf35849cfe9f315d85a787ff79b5675da6b1ed8c156f2c2c3e667b95596f9a5af30fb7dfec6dc6c5b99b105e87",
          "sha256": "d95bbd6dad2b89e85591cd9b66e837b9653442d76df3787ee4ec22a257bcfb0e",
          "sha1": "f4aacbad37ea7bcb8be630c796f1aa3daa91dc28",
          "md5": "763b085980a75f819ea02e3904d7b720"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PreloadingTricks-3.5.14.jar",
          "url": "PreloadingTricks-3.5.14.jar",
          "size": 1892165,
          "sha512": "89da391dd5091d9a6ceb88816f47c1388a0815bf35849cfe9f315d85a787ff79b5675da6b1ed8c156f2c2c3e667b95596f9a5af30fb7dfec6dc6c5b99b105e87",
          "sha256": "d95bbd6dad2b89e85591cd9b66e837b9653442d76df3787ee4ec22a257bcfb0e",
          "sha1": "f4aacbad37ea7bcb8be630c796f1aa3daa91dc28",
          "md5": "763b085980a75f819ea02e3904d7b720"
        }
      ]
    },
    {
      "name": "fabricApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.14-fabric.jar",
          "url": "PreloadingTricks-3.5.14-fabric.jar",
          "size": 836329,
          "sha512": "57f987e6a0634ac4936eeb4b1927964736e58f476ed36279b9f4c719f2c7f0e2c4e564b6c5e5e8ba64a44e92dbe7bc57ab79fb5462fe75b773a32f9348c552c6",
          "sha256": "db2e8fcecfd2ab3377ff8edce25f03b2fa0ddac331be31949deec694a4f43baf",
          "sha1": "b3a9f4113d0cc18b99b3fdbba3d05289aafcaa84",
          "md5": "6f0b47aac804ba7f347c5ae9e383ead9"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-fabric",
          "version": "3.5.14"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.14"
        }
      ]
    },
    {
      "name": "fabricRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.14-fabric.jar",
          "url": "PreloadingTricks-3.5.14-fabric.jar",
          "size": 836329,
          "sha512": "57f987e6a0634ac4936eeb4b1927964736e58f476ed36279b9f4c719f2c7f0e2c4e564b6c5e5e8ba64a44e92dbe7bc57ab79fb5462fe75b773a32f9348c552c6",
          "sha256": "db2e8fcecfd2ab3377ff8edce25f03b2fa0ddac331be31949deec694a4f43baf",
          "sha1": "b3a9f4113d0cc18b99b3fdbba3d05289aafcaa84",
          "md5": "6f0b47aac804ba7f347c5ae9e383ead9"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-fabric",
          "version": "3.5.14"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.14"
        }
      ]
    },
    {
      "name": "forgeServiceApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.14-forge-service.jar",
          "url": "PreloadingTricks-3.5.14-forge-service.jar",
          "size": 897143,
          "sha512": "3447230f6c92eac2eaad1900e9db18e23dd6d25da4cf18d2040d8ffe7e89bce0625e1660086d87c7015010638b5228be745ee92d192e48b5506e9ad5d1bddb5b",
          "sha256": "7e9316eb527827ddaa2d4a8c3487b4a691440294a4b4a5919f6111606f88f303",
          "sha1": "36cfa3bda5a92979948c0e453676a014a99186fb",
          "md5": "1684bd677efe6ee541f9844e130a26c9"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "3.5.14"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.14"
        }
      ]
    },
    {
      "name": "forgeServiceRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.14-forge-service.jar",
          "url": "PreloadingTricks-3.5.14-forge-service.jar",
          "size": 897143,
          "sha512": "3447230f6c92eac2eaad1900e9db18e23dd6d25da4cf18d2040d8ffe7e89bce0625e1660086d87c7015010638b5228be745ee92d192e48b5506e9ad5d1bddb5b",
          "sha256": "7e9316eb527827ddaa2d4a8c3487b4a691440294a4b4a5919f6111606f88f303",
          "sha1": "36cfa3bda5a92979948c0e453676a014a99186fb",
          "md5": "1684bd677efe6ee541f9844e130a26c9"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "3.5.14"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.14"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.14-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.5.14-neoforge-modlauncher.jar",
          "size": 896287,
          "sha512": "abb0c8e8c3ed0020d3cc701eba163b9b95950b88416af49d77ad42da4c954156c50cfe35ed5b4ff44b10d2430fb16dc0cfac3e3d9cb3389a161cba8429865a76",
          "sha256": "251026c6187cedb8cf8bdd8303cff2fc8ea1203ccef63bf5ac66e03c8a471b0e",
          "sha1": "fab6b6ec0dce4d0b876ac40d8effab8e582b74a3",
          "md5": "7eab905bb378623b96f2f255664fb038"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.14"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "3.5.14"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.14-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.5.14-neoforge-modlauncher.jar",
          "size": 896287,
          "sha512": "abb0c8e8c3ed0020d3cc701eba163b9b95950b88416af49d77ad42da4c954156c50cfe35ed5b4ff44b10d2430fb16dc0cfac3e3d9cb3389a161cba8429865a76",
          "sha256": "251026c6187cedb8cf8bdd8303cff2fc8ea1203ccef63bf5ac66e03c8a471b0e",
          "sha1": "fab6b6ec0dce4d0b876ac40d8effab8e582b74a3",
          "md5": "7eab905bb378623b96f2f255664fb038"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.14"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "3.5.14"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.14-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.5.14-neoforge-fancy-mod-loader.jar",
          "size": 69138,
          "sha512": "999a6b2f762fa65388914b863ca6aa2ab48fe0279a71daad092891cedebb6b8aefdac6fe13eb0264bceb435cfe40fb5ba51b78cdbe1d821c85167e8d36fd8aa3",
          "sha256": "f04305013e82809f5c023bfb5388d2f26d2ff91e20e08a416dc91a20333adc5b",
          "sha1": "f5df99666179c68846a1bb3f9e79a04d77e80612",
          "md5": "54716b3dfbd1318f0831d30a0b001d74"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "3.5.14"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.14"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.14-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.5.14-neoforge-fancy-mod-loader.jar",
          "size": 69138,
          "sha512": "999a6b2f762fa65388914b863ca6aa2ab48fe0279a71daad092891cedebb6b8aefdac6fe13eb0264bceb435cfe40fb5ba51b78cdbe1d821c85167e8d36fd8aa3",
          "sha256": "f04305013e82809f5c023bfb5388d2f26d2ff91e20e08a416dc91a20333adc5b",
          "sha1": "f5df99666179c68846a1bb3f9e79a04d77e80612",
          "md5": "54716b3dfbd1318f0831d30a0b001d74"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "3.5.14"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.14"
        }
      ]
    }
  ]
}
