{
  "formatVersion": "1.1",
  "component": {
    "group": "earth.terrarium",
    "module": "cloche",
    "version": "0.18.11-dust.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cloche-0.18.11-dust.7.jar",
          "url": "cloche-0.18.11-dust.7.jar",
          "size": 1154327,
          "sha512": "e52047dd73a02de2b95289a8bbc23e9e976ccdaa7dc1a3516954c5e85be3fdc7892cd0b351bfb4d476cc7a8225b64dfa1b5ed19d6e006e53e8a4477423aab23b",
          "sha256": "05650a402f1eba87e704a943d03e339d26b46fe91c8a32de2e1d667542e50bc7",
          "sha1": "cc736d6ff3729dcf3a253532d419ddfadb13fff0",
          "md5": "fdbf2e83e101bbf458605097a9ad3e4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-forge",
          "version": {
            "requires": "0.8.4-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-fabric",
          "version": {
            "requires": "0.7.0-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.8-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3-dust.3"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.1-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-decompiler",
          "version": {
            "requires": "0.6.0-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extensions-gradle-plugin",
          "version": {
            "requires": "1.0.12"
          }
        },
        {
          "group": "net.msrandom",
          "module": "jvm-virtual-source-sets",
          "version": {
            "requires": "1.3.6-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "classpath-api-stubs",
          "version": {
            "requires": "0.1.12-dust.1"
          }
        },
        {
          "group": "net.peanuuutz.tomlkt",
          "module": "tomlkt",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.18.11-dust.7.jar",
          "url": "cloche-0.18.11-dust.7.jar",
          "size": 1154327,
          "sha512": "e52047dd73a02de2b95289a8bbc23e9e976ccdaa7dc1a3516954c5e85be3fdc7892cd0b351bfb4d476cc7a8225b64dfa1b5ed19d6e006e53e8a4477423aab23b",
          "sha256": "05650a402f1eba87e704a943d03e339d26b46fe91c8a32de2e1d667542e50bc7",
          "sha1": "cc736d6ff3729dcf3a253532d419ddfadb13fff0",
          "md5": "fdbf2e83e101bbf458605097a9ad3e4d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.18.11-dust.7-javadoc.jar",
          "url": "cloche-0.18.11-dust.7-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.18.11-dust.7-sources.jar",
          "url": "cloche-0.18.11-dust.7-sources.jar",
          "size": 87156,
          "sha512": "b64500855f15edd9e3d16643877287f8802eefffc6bc6a6ef8119c98e2f3fd92e29155014354f221e0d043349bf74d639ebf2823aca477ac6bc3fc01638ff1b4",
          "sha256": "ed0ee6d7c8ecb6379bf6b60b76696c911feab450c7b3b880342ab2d62a6c89bd",
          "sha1": "dea0bf16739126f6e5075dcdab7c1bf9ed7eafdc",
          "md5": "9041548203cf9d266ada1d86a5f575df"
        }
      ]
    }
  ]
}
