{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-mixins",
    "version": "0.6.1-dust.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.17.0+mixin.0.8.7"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-mixins-0.6.1-dust.1.jar",
          "url": "minecraft-codev-mixins-0.6.1-dust.1.jar",
          "size": 65747,
          "sha512": "00b17d4e0992bed01d9cde3e0c26ffbb28ff4b5bd6160a9449b0bc38fb3af0d40287f9f1b949e90402987a10f1dde1f72807c7295a7fa641f2d83a5e0de3b107",
          "sha256": "568180e7817cdf58607816aa98036447b01e89c707d990e3bece7c9c0066876e",
          "sha1": "022b8b4964f3ea77aff1b97178479c3510e5ba0b",
          "md5": "068f0a550cf6bc6ca511e9eb8767d3d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.17.0+mixin.0.8.7"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-mixins-0.6.1-dust.1.jar",
          "url": "minecraft-codev-mixins-0.6.1-dust.1.jar",
          "size": 65747,
          "sha512": "00b17d4e0992bed01d9cde3e0c26ffbb28ff4b5bd6160a9449b0bc38fb3af0d40287f9f1b949e90402987a10f1dde1f72807c7295a7fa641f2d83a5e0de3b107",
          "sha256": "568180e7817cdf58607816aa98036447b01e89c707d990e3bece7c9c0066876e",
          "sha1": "022b8b4964f3ea77aff1b97178479c3510e5ba0b",
          "md5": "068f0a550cf6bc6ca511e9eb8767d3d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-mixins-0.6.1-dust.1-sources.jar",
          "url": "minecraft-codev-mixins-0.6.1-dust.1-sources.jar",
          "size": 15350,
          "sha512": "235f70e38cd3073bac7431fdf53cd78ee225d5f089f59eb336d95928931fd2a6e2ffbd44293fb3df36cf1c8c3f466f3fcf14859a7027c85394a5972f0dfc6ea6",
          "sha256": "4fc8e4620978793ff1c63bff483699c85ebb2141618f84a397c7dfc57a99ff5f",
          "sha1": "0c6a6cf86e2920272e802904abdaaa201a5b0fbf",
          "md5": "7cc7f5d641f9afa0567b2c9c34c3901f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-mixins-0.6.1-dust.1-javadoc.jar",
          "url": "minecraft-codev-mixins-0.6.1-dust.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
