{
  "formatVersion": "1.1",
  "component": {
    "group": "earth.terrarium",
    "module": "cloche",
    "version": "0.18.14-dust.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cloche-0.18.14-dust.2.jar",
          "url": "cloche-0.18.14-dust.2.jar",
          "size": 1157185,
          "sha512": "c68da6690716224396e55e384a5b4304235d5eba2132c6a6e47707b3cd13d63e147e26bd6d0ac903e3c3cf97998ef22cdfa142bc741d00cdfb856cbe8d0904de",
          "sha256": "49f21a65e86624b8f5dd3738a0834ff70fa4367cbf4b0e3628f642c5dc6ac81a",
          "sha1": "21e483d3d6277af58516d5810b6a52241c378497",
          "md5": "e48b055f4bc1ccd04190cd06fdd5aac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-forge",
          "version": {
            "requires": "0.8.4-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-fabric",
          "version": {
            "requires": "0.7.0-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.8-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3-dust.3"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.1-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-decompiler",
          "version": {
            "requires": "0.6.0-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extensions-gradle-plugin",
          "version": {
            "requires": "1.0.12"
          }
        },
        {
          "group": "net.msrandom",
          "module": "jvm-virtual-source-sets",
          "version": {
            "requires": "1.3.6-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "classpath-api-stubs",
          "version": {
            "requires": "0.1.12-dust.5"
          }
        },
        {
          "group": "net.peanuuutz.tomlkt",
          "module": "tomlkt",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.18.14-dust.2.jar",
          "url": "cloche-0.18.14-dust.2.jar",
          "size": 1157185,
          "sha512": "c68da6690716224396e55e384a5b4304235d5eba2132c6a6e47707b3cd13d63e147e26bd6d0ac903e3c3cf97998ef22cdfa142bc741d00cdfb856cbe8d0904de",
          "sha256": "49f21a65e86624b8f5dd3738a0834ff70fa4367cbf4b0e3628f642c5dc6ac81a",
          "sha1": "21e483d3d6277af58516d5810b6a52241c378497",
          "md5": "e48b055f4bc1ccd04190cd06fdd5aac5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.18.14-dust.2-javadoc.jar",
          "url": "cloche-0.18.14-dust.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.18.14-dust.2-sources.jar",
          "url": "cloche-0.18.14-dust.2-sources.jar",
          "size": 87602,
          "sha512": "bce023eb9ba3d3c03c16a7d3301e1261fd330a2e8e60fac22e205a606955806e7b8ab4bba72b6f903c40cf74bfae6940aee1e97ecd95225e91db40bee054b376",
          "sha256": "8a522ba03d87c00af238e9e49cc94ef971862af23e2038f1062e0bb42aa15f35",
          "sha1": "69c294a2086a5acbb439ed10f2f64658ebaa5c12",
          "md5": "6906c175806ccf7c6534a484767bb2e2"
        }
      ]
    }
  ]
}
