{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-access-widener",
    "version": "0.6.3-dust.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0-beta.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.2.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.2.jar",
          "size": 88513,
          "sha512": "9ba48766661c6e07018dfb9b9b2789fb358106d57e3eb1c5e7a632d3468429d0062f34ab54b3dfebd6b4bc603ec8dd9abe9432a41599ad81b4fca8313d883eb8",
          "sha256": "d2db6ce3fcded111e95dac3c1377c40c511d76e88a4966daad0b4277a314aa32",
          "sha1": "af9c6e98f40d2aa5b41b678185093f324573f4da",
          "md5": "fc239e54b904e72dce3485a92e6fa02b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0-beta.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.2.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.2.jar",
          "size": 88513,
          "sha512": "9ba48766661c6e07018dfb9b9b2789fb358106d57e3eb1c5e7a632d3468429d0062f34ab54b3dfebd6b4bc603ec8dd9abe9432a41599ad81b4fca8313d883eb8",
          "sha256": "d2db6ce3fcded111e95dac3c1377c40c511d76e88a4966daad0b4277a314aa32",
          "sha1": "af9c6e98f40d2aa5b41b678185093f324573f4da",
          "md5": "fc239e54b904e72dce3485a92e6fa02b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.2-sources.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.2-sources.jar",
          "size": 8380,
          "sha512": "19ebdcf7b63a536e89d2c7610ba41561f173bcc2b4b72532d00e5a2000324f37c8aef49aa1be179700cd44ca258e367353f36e949b1671914d8b44394cb8b0b0",
          "sha256": "2cbd09aa84f5b68d67edc08bb9eb54a8190b37ffea6feea2758286e98c7bd2c3",
          "sha1": "61e3b3daad7aed771161eae0fd97bceb468b5fc4",
          "md5": "5c5ac5b858f9790966c230356b5797f8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.2-javadoc.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
