{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-forge",
    "version": "0.8.4-dust.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.4-dust.1.jar",
          "url": "minecraft-codev-forge-0.8.4-dust.1.jar",
          "size": 306899,
          "sha512": "8690b71651a9a719be290571d36ab42c5f8834a05339b6ad504cbe4ae1124de9edcf747b779b17fbc0ff1c9042c350d3433a7e399447ca0f80bfbd4d8c0bebc4",
          "sha256": "8fd48a4253b5c336456d10eb098b5c5275cada34b965ecf8171e590909143300",
          "sha1": "948661b5d23b67cd20103afac1bd49dc94eb3526",
          "md5": "d6f5ce664bc7fa6e8a70752ac392b729"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core-serialization",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-cli",
          "version": {
            "requires": "13.0.3"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3-dust.3"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.1-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.8-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.4-dust.1.jar",
          "url": "minecraft-codev-forge-0.8.4-dust.1.jar",
          "size": 306899,
          "sha512": "8690b71651a9a719be290571d36ab42c5f8834a05339b6ad504cbe4ae1124de9edcf747b779b17fbc0ff1c9042c350d3433a7e399447ca0f80bfbd4d8c0bebc4",
          "sha256": "8fd48a4253b5c336456d10eb098b5c5275cada34b965ecf8171e590909143300",
          "sha1": "948661b5d23b67cd20103afac1bd49dc94eb3526",
          "md5": "d6f5ce664bc7fa6e8a70752ac392b729"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.4-dust.1-sources.jar",
          "url": "minecraft-codev-forge-0.8.4-dust.1-sources.jar",
          "size": 36841,
          "sha512": "b07d968f3e5a8c8250d462d65765cc867d3e022ff0cb0a311db1d6501867fda6de8623956173e690ea0170e4df35d2f8a1e6773e80a193f0c7cc406d9219545f",
          "sha256": "232e50168b01a414ec2eca00ccf9b8fca24a4960f35a22afe8e03a9ef5fba761",
          "sha1": "9d1a5b18079a53b07956e73a2827d25e7c301d65",
          "md5": "81592501ae3777e42a5c74bea5bf76ec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.4-dust.1-javadoc.jar",
          "url": "minecraft-codev-forge-0.8.4-dust.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
