{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-runs",
    "version": "0.7.2-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext",
          "module": "gradle-idea-ext",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-runs-0.7.2-dust.0.jar",
          "url": "minecraft-codev-runs-0.7.2-dust.0.jar",
          "size": 125452,
          "sha512": "440ee31d963acd750c4f4815ec4fa6a93b50d5e3fe49972fafdb460db101cbddd94d8c5785388a6289d766e145b1f7d387095a69195ea85d9e77aad9a9e75663",
          "sha256": "7f808a1bb54b8a2f2d35997681c5dfd925f872c89ebb7ab19d76a18a31a2bc4c",
          "sha1": "73d7e33ddb7e4e4fd0d0e5413e2acf66b9d66601",
          "md5": "4ee98be782e1e6a66397576ce2f8053a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.7.2-dust.0"
          }
        },
        {
          "group": "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext",
          "module": "gradle-idea-ext",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-runs-0.7.2-dust.0.jar",
          "url": "minecraft-codev-runs-0.7.2-dust.0.jar",
          "size": 125452,
          "sha512": "440ee31d963acd750c4f4815ec4fa6a93b50d5e3fe49972fafdb460db101cbddd94d8c5785388a6289d766e145b1f7d387095a69195ea85d9e77aad9a9e75663",
          "sha256": "7f808a1bb54b8a2f2d35997681c5dfd925f872c89ebb7ab19d76a18a31a2bc4c",
          "sha1": "73d7e33ddb7e4e4fd0d0e5413e2acf66b9d66601",
          "md5": "4ee98be782e1e6a66397576ce2f8053a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-runs-0.7.2-dust.0-sources.jar",
          "url": "minecraft-codev-runs-0.7.2-dust.0-sources.jar",
          "size": 14305,
          "sha512": "02a0702182149f00bd98a18d91835fd2ec73f7c15f2b0988411f3b2887aecf1784aca7410406e64a816a37afc0c7f1571fccd3cea02a19fee7c4f98d1b3eef86",
          "sha256": "fb8196858749fcbdcc4f2e01db8c5fc6a40ffe6c38b0898fba3bbf4b1a3d64ab",
          "sha1": "b136a59912cbc3efadff50b3e97ffa417a00d88d",
          "md5": "e1737d99513242378b8957b53bf21c85"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-runs-0.7.2-dust.0-javadoc.jar",
          "url": "minecraft-codev-runs-0.7.2-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
