{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-core",
    "version": "0.6.9-dust.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-core-0.6.9-dust.2.jar",
          "url": "minecraft-codev-core-0.6.9-dust.2.jar",
          "size": 311058,
          "sha512": "211e2a7c49d1549ed36878b27e8d4b28f4f42e8d9d22e02ac0103955f77f4618bc49133c7b7a5e1adcfe84f0116b3674bcdd98e46207e8dc0083b220f85cf66a",
          "sha256": "db9b4049947e793a45b63c5e1de96288b18bd30d164f77c0ac91f808265ed0f2",
          "sha1": "399d5818eaeab38a6b35fb22b7eb9fb4da7cd488",
          "md5": "cec7fc9881d527edd312736258059a41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "side-annotations",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-core-0.6.9-dust.2.jar",
          "url": "minecraft-codev-core-0.6.9-dust.2.jar",
          "size": 311058,
          "sha512": "211e2a7c49d1549ed36878b27e8d4b28f4f42e8d9d22e02ac0103955f77f4618bc49133c7b7a5e1adcfe84f0116b3674bcdd98e46207e8dc0083b220f85cf66a",
          "sha256": "db9b4049947e793a45b63c5e1de96288b18bd30d164f77c0ac91f808265ed0f2",
          "sha1": "399d5818eaeab38a6b35fb22b7eb9fb4da7cd488",
          "md5": "cec7fc9881d527edd312736258059a41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-core-0.6.9-dust.2-sources.jar",
          "url": "minecraft-codev-core-0.6.9-dust.2-sources.jar",
          "size": 34762,
          "sha512": "7934597ecf32bb163abe6f63ab58ef869fd11a1d11c07bb1a01e1a101a55701c209699dc4024e4f3cd67737d2333d250b6fc75ad46978bb3fe8bf00be4214c27",
          "sha256": "5ea91a3d457a939c8fe15977d8f1655222ed6a1bae58a1a20dd3967216761457",
          "sha1": "a4efb51d4d68e20ed9f4e4435f9168ad0f0a5cd6",
          "md5": "d7b0ae780015a614fa02954d4f7712af"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-core-0.6.9-dust.2-javadoc.jar",
          "url": "minecraft-codev-core-0.6.9-dust.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
