{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-core",
    "version": "0.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-core-0.6.6.jar",
          "url": "minecraft-codev-core-0.6.6.jar",
          "size": 303893,
          "sha512": "da9da6a7bb7dedc64353a66e85d1c7ba8f3b708224bacaf72c1f3f57d27c9092fcff607ef4add43cce234bf9ec839f14596592b18c17dfe71800ef4ac5eefdfe",
          "sha256": "15c85b22f6019175a2bba43a2fe2a5281f40c122b02591d2236b897afb055f8f",
          "sha1": "7fa07d684b3a6bb487bf50e933ce15642340266a",
          "md5": "b129a71e8ba9730636229492224c1c00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "side-annotations",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-core-0.6.6.jar",
          "url": "minecraft-codev-core-0.6.6.jar",
          "size": 303893,
          "sha512": "da9da6a7bb7dedc64353a66e85d1c7ba8f3b708224bacaf72c1f3f57d27c9092fcff607ef4add43cce234bf9ec839f14596592b18c17dfe71800ef4ac5eefdfe",
          "sha256": "15c85b22f6019175a2bba43a2fe2a5281f40c122b02591d2236b897afb055f8f",
          "sha1": "7fa07d684b3a6bb487bf50e933ce15642340266a",
          "md5": "b129a71e8ba9730636229492224c1c00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-core-0.6.6-sources.jar",
          "url": "minecraft-codev-core-0.6.6-sources.jar",
          "size": 32358,
          "sha512": "25d5e49f5a3a37954a2d5b1a9342c27a9f60023e17a75e91e7da5d7150302daa422651159a27cca57ef7e2218c55a2a990c637ae17083f75a98b32fb17bd3a11",
          "sha256": "31d5d738ae4208b6daf17a18f62750f8addbc8d09ea60771e395e0836ea79578",
          "sha1": "c22c78e51eaaccf57b2d781b904e94ac318d09b0",
          "md5": "6e0c86f851388b465e13f3db80290871"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-core-0.6.6-javadoc.jar",
          "url": "minecraft-codev-core-0.6.6-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
