{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-remapper",
    "version": "0.7.2-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.7.2-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-remapper-0.7.2-dust.0.jar",
          "url": "minecraft-codev-remapper-0.7.2-dust.0.jar",
          "size": 181775,
          "sha512": "0c008ffd2af1d8a67397124c590eef78db7c1a67ef916304b6733ef4530353dde1b7249c88338f1f73972f646d513919b1ac7db2dab741ea6527173d0e61e135",
          "sha256": "7a34cd711de3ebe727688a4cbb8956584ea37b88906478af7f395dc2bc307df5",
          "sha1": "8c512ffaa91293f1f60c395ba19ffd75e6131166",
          "md5": "e977c53f0d41a29375a604ac85c9dc66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.7.2-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-remapper-0.7.2-dust.0.jar",
          "url": "minecraft-codev-remapper-0.7.2-dust.0.jar",
          "size": 181775,
          "sha512": "0c008ffd2af1d8a67397124c590eef78db7c1a67ef916304b6733ef4530353dde1b7249c88338f1f73972f646d513919b1ac7db2dab741ea6527173d0e61e135",
          "sha256": "7a34cd711de3ebe727688a4cbb8956584ea37b88906478af7f395dc2bc307df5",
          "sha1": "8c512ffaa91293f1f60c395ba19ffd75e6131166",
          "md5": "e977c53f0d41a29375a604ac85c9dc66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-remapper-0.7.2-dust.0-sources.jar",
          "url": "minecraft-codev-remapper-0.7.2-dust.0-sources.jar",
          "size": 20576,
          "sha512": "b169b65d8e1deacb5c4b721713ed389378e2b63d714fe5e3da3e9698387d78edaa46e94ffac50d7df2344e41e87a075dcfc06da3ebd73a344768af3475d935f8",
          "sha256": "e7d57e4b946076792673854a7afb4719ad6735936c16c40500eb0dadd5e760ec",
          "sha1": "71acf263c3380ccd26855a7fe54b6c9b2f18bd1f",
          "md5": "ec4854f742a8520c3fbd991a7209fd17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-remapper-0.7.2-dust.0-javadoc.jar",
          "url": "minecraft-codev-remapper-0.7.2-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
