{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "codev-forge-runtime",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "codev-forge-runtime-0.1.1.jar",
          "url": "codev-forge-runtime-0.1.1.jar",
          "size": 6798,
          "sha512": "cf25c7faf517928b59f2e1b053f99713b86b46b4dbdcc0661a1af7490f8fb7b372b6d6406a4334c527fe9e0c1b41ce846e3eeba71ed1fd3d3b537641a07d450f",
          "sha256": "c52da7339f39521c9fd4437eace623c539b5bd949794cd0ebbf181b45554f643",
          "sha1": "da993780e5b0c419dd6436d92c441f59513563d5",
          "md5": "9d2094f27068c50c5ab019ad5297a7b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "8.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "codev-forge-runtime-0.1.1.jar",
          "url": "codev-forge-runtime-0.1.1.jar",
          "size": 6798,
          "sha512": "cf25c7faf517928b59f2e1b053f99713b86b46b4dbdcc0661a1af7490f8fb7b372b6d6406a4334c527fe9e0c1b41ce846e3eeba71ed1fd3d3b537641a07d450f",
          "sha256": "c52da7339f39521c9fd4437eace623c539b5bd949794cd0ebbf181b45554f643",
          "sha1": "da993780e5b0c419dd6436d92c441f59513563d5",
          "md5": "9d2094f27068c50c5ab019ad5297a7b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codev-forge-runtime-0.1.1-sources.jar",
          "url": "codev-forge-runtime-0.1.1-sources.jar",
          "size": 2680,
          "sha512": "96755ca7204b34a2598d5b48408b20b2aaa7e310c134c82cc2a5dbbb32b4eb67e0693137f20d2b038939ff4419fc237f0cac367a0fdaa1c0db681c1f60eb8de9",
          "sha256": "d7b136746709e467465fef06d4f7b81739b54f2af40c0276057a9370ccc13103",
          "sha1": "3c7341c15b791999ad5c9d213e35454f988879d3",
          "md5": "b81e74d0a9e76d0c5dd526c367a296ea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codev-forge-runtime-0.1.1-javadoc.jar",
          "url": "codev-forge-runtime-0.1.1-javadoc.jar",
          "size": 19716,
          "sha512": "a3b63530a1bd15d2dd859d824983d01ec31383010308a02d02400fcbe7429aa3416fdc91cdd6e9cc33506b6a6963d29488f40cedcb19f86c7b4ed38b3980c737",
          "sha256": "812e45e665f05059082656da6cf6a0679a02ed0de30adf9598023ae176523967",
          "sha1": "33dd81ba3a5931f9fcc34720e91bf5ec0b1790da",
          "md5": "fb49c3726f171991526b142162c11bf8"
        }
      ]
    }
  ]
}
