{
  "formatVersion": "1.1",
  "component": {
    "group": "settingdust.preloading_tricks",
    "module": "PreloadingTricks",
    "version": "3.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      }
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PreloadingTricks-3.7.1.jar",
          "url": "PreloadingTricks-3.7.1.jar",
          "size": 1758882,
          "sha512": "76a3194aa33cbb1a9cc2101cd09a8e4cdb10180bfeac8c1562ed443a2bc93317fe55abd1d13afae030323d8dd5a756e986154f3066d76999a476187c34799c33",
          "sha256": "4b0c8f251dff0cd2720e6687e5bbd9e497475deb76402898cd5707e63c37e90f",
          "sha1": "e0585978cfbe4c8d3cb3d327e03dcd6b175d4921",
          "md5": "d90fd4b41eab5126743d4330bfd110d3"
        }
      ]
    },
    {
      "name": "platformFabricApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.7.1-platform-fabric.jar",
          "url": "PreloadingTricks-3.7.1-platform-fabric.jar",
          "size": 835761,
          "sha512": "5ec4d41d0ea2fc1460a3ff9bb7f32981cff859f1feb3f577cff8952ae582aa4fe644b0458e35ede0a9b28d0360233e380a13e0846dddfb5931a996f97eda8f71",
          "sha256": "1c8dc83f49029188c8afeb3a5167e8837fb0c5c123e7966da6ca3d8dd0d76440",
          "sha1": "3bec26ebc7ff152bae31ae360ed22488f6797f8c",
          "md5": "f0af5492eddce755134e9c415deb4e7f"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.7.1"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-platform-fabric",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "platformFabricRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.7+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.7.1-platform-fabric.jar",
          "url": "PreloadingTricks-3.7.1-platform-fabric.jar",
          "size": 835761,
          "sha512": "5ec4d41d0ea2fc1460a3ff9bb7f32981cff859f1feb3f577cff8952ae582aa4fe644b0458e35ede0a9b28d0360233e380a13e0846dddfb5931a996f97eda8f71",
          "sha256": "1c8dc83f49029188c8afeb3a5167e8837fb0c5c123e7966da6ca3d8dd0d76440",
          "sha1": "3bec26ebc7ff152bae31ae360ed22488f6797f8c",
          "md5": "f0af5492eddce755134e9c415deb4e7f"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.7.1"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-platform-fabric",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "platformForgeModlauncherApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.7.1-platform-forge-modlauncher.jar",
          "url": "PreloadingTricks-3.7.1-platform-forge-modlauncher.jar",
          "size": 895941,
          "sha512": "c7642736ae908e607ab205c677d81ee05a340104263b91a24ccfbc897a3bd5e7042f6884a6e7418bbf583e49a7085bf54cd161e79a31df40e8d8c9796248c125",
          "sha256": "89a91f5180fe679b1e2b2ca09e718c5a82567e0281593d1db69168dbb49105b1",
          "sha1": "42ac77a5a0896d170d3c2011cc4d3c4303f50323",
          "md5": "90a7d917dfadb94ce09c6da63024a101"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.7.1"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-platform-forge-modlauncher",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "platformForgeModlauncherRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.7.1-platform-forge-modlauncher.jar",
          "url": "PreloadingTricks-3.7.1-platform-forge-modlauncher.jar",
          "size": 895941,
          "sha512": "c7642736ae908e607ab205c677d81ee05a340104263b91a24ccfbc897a3bd5e7042f6884a6e7418bbf583e49a7085bf54cd161e79a31df40e8d8c9796248c125",
          "sha256": "89a91f5180fe679b1e2b2ca09e718c5a82567e0281593d1db69168dbb49105b1",
          "sha1": "42ac77a5a0896d170d3c2011cc4d3c4303f50323",
          "md5": "90a7d917dfadb94ce09c6da63024a101"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.7.1"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-platform-forge-modlauncher",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "platformNeoforgeModlauncherApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.7.1-platform-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.7.1-platform-neoforge-modlauncher.jar",
          "size": 895397,
          "sha512": "195178265e77f14bb990368319579c4ac78613622d01771137c12aec7fb20f7da8f86cc1c7db924decee0478b13fbeaaf5e131f6da3b0492e15da68a95466b9a",
          "sha256": "45e309503c3c5ea9a87d07487bb2815fc44c35dbe631da6a09c3a332712551d6",
          "sha1": "a797854f8ce98ca147dfe9a300c5f9a9b3fd2f97",
          "md5": "b4147c715b062d5afb588a55bdcc0769"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.7.1"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-platform-neoforge-modlauncher",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "platformNeoforgeModlauncherRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.7.1-platform-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.7.1-platform-neoforge-modlauncher.jar",
          "size": 895397,
          "sha512": "195178265e77f14bb990368319579c4ac78613622d01771137c12aec7fb20f7da8f86cc1c7db924decee0478b13fbeaaf5e131f6da3b0492e15da68a95466b9a",
          "sha256": "45e309503c3c5ea9a87d07487bb2815fc44c35dbe631da6a09c3a332712551d6",
          "sha1": "a797854f8ce98ca147dfe9a300c5f9a9b3fd2f97",
          "md5": "b4147c715b062d5afb588a55bdcc0769"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.7.1"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-platform-neoforge-modlauncher",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "platformNeoforgeFancyModLoaderApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "26.1.2",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "26.1.2",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.7.1-platform-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.7.1-platform-neoforge-fancy-mod-loader.jar",
          "size": 853311,
          "sha512": "9dce8425493df919ae3751d78293db7b9f16ccffa5068bef3ca2a896d9b6d785ae09655c9679cd81ce3c8bc4c067f9c410cbcab5b4cf42056df6af5ab0a8471b",
          "sha256": "9445a413d1b4a4582db64be6224ffe4dc11528064bca185cce8bc19d712f3c2f",
          "sha1": "3e3bf1a74cd65b78af5a2d6592287d09070331c7",
          "md5": "3c7afdee7b7c0bd1f0e52f025d8ee31c"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.7.1"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-platform-neoforge-fancy-mod-loader",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "platformNeoforgeFancyModLoaderRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "26.1.2",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.14-dust.2",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "26.1.2",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.7.1-platform-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.7.1-platform-neoforge-fancy-mod-loader.jar",
          "size": 853311,
          "sha512": "9dce8425493df919ae3751d78293db7b9f16ccffa5068bef3ca2a896d9b6d785ae09655c9679cd81ce3c8bc4c067f9c410cbcab5b4cf42056df6af5ab0a8471b",
          "sha256": "9445a413d1b4a4582db64be6224ffe4dc11528064bca185cce8bc19d712f3c2f",
          "sha1": "3e3bf1a74cd65b78af5a2d6592287d09070331c7",
          "md5": "3c7afdee7b7c0bd1f0e52f025d8ee31c"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.7.1"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-platform-neoforge-fancy-mod-loader",
          "version": "3.7.1"
        }
      ]
    }
  ]
}
