{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-remapper",
    "version": "0.7.1-dust.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-remapper-0.7.1-dust.3.jar",
          "url": "minecraft-codev-remapper-0.7.1-dust.3.jar",
          "size": 181816,
          "sha512": "2e2a1070f648d372f01679ab5eecbd6157b1c778e968fb2c2e07c8feac0fac0bfb73f0f8f2fd88f697b7908653fe789fe3eb736e6c60df6ad79df9bc012f856a",
          "sha256": "21f267fd2bfbe8da84de04c3dd58ba8ec62e1d01b5f78d9661f6476ee4494b60",
          "sha1": "4e0b023d7beec382ddc5c7c7f39ce38c29e016b3",
          "md5": "4b43547048b561150527634bec514387"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-remapper-0.7.1-dust.3.jar",
          "url": "minecraft-codev-remapper-0.7.1-dust.3.jar",
          "size": 181816,
          "sha512": "2e2a1070f648d372f01679ab5eecbd6157b1c778e968fb2c2e07c8feac0fac0bfb73f0f8f2fd88f697b7908653fe789fe3eb736e6c60df6ad79df9bc012f856a",
          "sha256": "21f267fd2bfbe8da84de04c3dd58ba8ec62e1d01b5f78d9661f6476ee4494b60",
          "sha1": "4e0b023d7beec382ddc5c7c7f39ce38c29e016b3",
          "md5": "4b43547048b561150527634bec514387"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-remapper-0.7.1-dust.3-sources.jar",
          "url": "minecraft-codev-remapper-0.7.1-dust.3-sources.jar",
          "size": 20576,
          "sha512": "b169b65d8e1deacb5c4b721713ed389378e2b63d714fe5e3da3e9698387d78edaa46e94ffac50d7df2344e41e87a075dcfc06da3ebd73a344768af3475d935f8",
          "sha256": "e7d57e4b946076792673854a7afb4719ad6735936c16c40500eb0dadd5e760ec",
          "sha1": "71acf263c3380ccd26855a7fe54b6c9b2f18bd1f",
          "md5": "ec4854f742a8520c3fbd991a7209fd17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-remapper-0.7.1-dust.3-javadoc.jar",
          "url": "minecraft-codev-remapper-0.7.1-dust.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
