{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-runs",
    "version": "0.6.8-dust.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext",
          "module": "gradle-idea-ext",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-runs-0.6.8-dust.1.jar",
          "url": "minecraft-codev-runs-0.6.8-dust.1.jar",
          "size": 120322,
          "sha512": "b739642d7ad24b822bd5de7c6118ad1f74ea01d8477125ac2a77add72a97ff2f48ae63839629fa68fec747e2454b70be5d94411326f0eec0898591b3ca1245e0",
          "sha256": "619bb037aff502e351e3152acbe1c15b129228cac6823084248049c9b1d5fce7",
          "sha1": "85cd8f828926672317c4b0dab51650f59a7ae31a",
          "md5": "401387d1bc494aa80a3781d4a4787252"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.1"
          }
        },
        {
          "group": "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext",
          "module": "gradle-idea-ext",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-runs-0.6.8-dust.1.jar",
          "url": "minecraft-codev-runs-0.6.8-dust.1.jar",
          "size": 120322,
          "sha512": "b739642d7ad24b822bd5de7c6118ad1f74ea01d8477125ac2a77add72a97ff2f48ae63839629fa68fec747e2454b70be5d94411326f0eec0898591b3ca1245e0",
          "sha256": "619bb037aff502e351e3152acbe1c15b129228cac6823084248049c9b1d5fce7",
          "sha1": "85cd8f828926672317c4b0dab51650f59a7ae31a",
          "md5": "401387d1bc494aa80a3781d4a4787252"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-runs-0.6.8-dust.1-sources.jar",
          "url": "minecraft-codev-runs-0.6.8-dust.1-sources.jar",
          "size": 12718,
          "sha512": "461b0560c5cb4e8fe34596c537ec34723a4ff665fdb7d2c994bb426c5f0f3ca887d8269389bf40179f2aec59d3dede7f03f8aac98eda4b5f8cc37cf0df945821",
          "sha256": "7200de50705313923a0a2a65cc17dd2d4da0733901594a98088a0fdab1066278",
          "sha1": "d8ba92508cc65f22d3c29178c43ae8c1fb960741",
          "md5": "9705cfa35d64e48bd6911898d378dbe4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-runs-0.6.8-dust.1-javadoc.jar",
          "url": "minecraft-codev-runs-0.6.8-dust.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
