{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "class-extensions-gradle-plugin",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "class-extensions-gradle-plugin-1.0.12.jar",
          "url": "class-extensions-gradle-plugin-1.0.12.jar",
          "size": 4561,
          "sha512": "ac54e1bdf5c377e9df9830748f7e78eeb44ef992a00f8a77bdc6c766b016c5bbef29410f7fbd5ebce3764fb51a53010bb944d00b611336b64e63a01bf497aff1",
          "sha256": "d98b4d7635d08e97d3ec2056bcaf746b0230cb0e98f3199c9b90c03febd282dc",
          "sha1": "508345ff8819db26cf3c48f4f48970a725b851bd",
          "md5": "da6cfa7a2cb69de11fc036c2daa7c61f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "class-extensions-gradle-plugin-1.0.12.jar",
          "url": "class-extensions-gradle-plugin-1.0.12.jar",
          "size": 4561,
          "sha512": "ac54e1bdf5c377e9df9830748f7e78eeb44ef992a00f8a77bdc6c766b016c5bbef29410f7fbd5ebce3764fb51a53010bb944d00b611336b64e63a01bf497aff1",
          "sha256": "d98b4d7635d08e97d3ec2056bcaf746b0230cb0e98f3199c9b90c03febd282dc",
          "sha1": "508345ff8819db26cf3c48f4f48970a725b851bd",
          "md5": "da6cfa7a2cb69de11fc036c2daa7c61f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "class-extensions-gradle-plugin-1.0.12-sources.jar",
          "url": "class-extensions-gradle-plugin-1.0.12-sources.jar",
          "size": 1126,
          "sha512": "80ec8ae6255340cc5e73036c6024df4f4bf7fda1163ec721f063202d8b5c3cdd1459f35e7f0b05b8ac60fe8e0029e3b0b7478fd8f5199194b151bcef4d530f56",
          "sha256": "8d254d997589666c177a1be0f34b1c2a2d0f390080e98d29b5cd1f7debb81085",
          "sha1": "2bc9466f135bc2b21c93e5f8435b96f0fc2fd00f",
          "md5": "1df2bf980ed6e8b2882869da03617968"
        }
      ]
    }
  ]
}
