{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "java-class-extensions-processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-class-extensions-processor-1.0.0.jar",
          "url": "java-class-extensions-processor-1.0.0.jar",
          "size": 10016,
          "sha512": "1963a8709abaad48da66e1239f16611bb89ce27452a536656ae02526b9fbddacf919eeed82340a99a1be4c8f40ce4940e48cf001f15854d69422fa8e4f94b8e3",
          "sha256": "d407e246a268c3fc042ece75ffaa5ed0f7b6ecf4883e74bae0c0c70cde4add99",
          "sha1": "91630dad18b6ebe7ecc4b74ca636596edda719f4",
          "md5": "d795fe7418c775364e698c2459ba5b2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "class-extension-annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "java-processor-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-class-extensions-processor-1.0.0.jar",
          "url": "java-class-extensions-processor-1.0.0.jar",
          "size": 10016,
          "sha512": "1963a8709abaad48da66e1239f16611bb89ce27452a536656ae02526b9fbddacf919eeed82340a99a1be4c8f40ce4940e48cf001f15854d69422fa8e4f94b8e3",
          "sha256": "d407e246a268c3fc042ece75ffaa5ed0f7b6ecf4883e74bae0c0c70cde4add99",
          "sha1": "91630dad18b6ebe7ecc4b74ca636596edda719f4",
          "md5": "d795fe7418c775364e698c2459ba5b2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-class-extensions-processor-1.0.0-sources.jar",
          "url": "java-class-extensions-processor-1.0.0-sources.jar",
          "size": 2709,
          "sha512": "342abe88a627ae9b41ace5c12fc1040ef9fee088a2d1de9785b6c922b35adcc909e29ff51f64c17eeae8347150cde09c6b06a6e1281edbd12f5a69b5a17bba5f",
          "sha256": "bae7d74dba3246f95e1fc11fc18363bfe335e0bfcb6e9e312ce6621e2e90d2fc",
          "sha1": "9213f0849e45bc13c79415f377c25f29df791d8a",
          "md5": "b8bb64fa734c5abcfb049dec741a4f0b"
        }
      ]
    }
  ]
}
