{
  "formatVersion": "1.1",
  "component": {
    "group": "settingdust.preloading_tricks",
    "module": "PreloadingTricks",
    "version": "3.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-3.5.8.jar",
          "url": "PreloadingTricks-3.5.8.jar",
          "size": 1884649,
          "sha512": "1cab02cdf17ad17f36fe81429a018c20a7e8bfef52ffb50fc8c3fb8b33cd22022f53b78ac0c6aa43af3a4401781741ca8a37cb2fa9f7f5273ee7168310350512",
          "sha256": "9473048fb8b816228ebec1d5554c21ff6cd5c357f0266da54e1aa463c5a30848",
          "sha1": "f0b0e90cf45766c058cc6700a135179863588978",
          "md5": "1c191df196a6c7923195df1bfbca500f"
        }
      ]
    },
    {
      "name": "fabricApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-fabric.jar",
          "url": "PreloadingTricks-3.5.8-fabric.jar",
          "size": 892533,
          "sha512": "e704e8e881c39d8d89ea03a812d0c64dbacfccecaf902154ba28fbc528f6b624cde861295d5051a61454859daecf80c5258f768342a210f54051a7a93197e13e",
          "sha256": "88f5eda30815b2a0ef8164cbbb12d151f2cefc706dd85067ca59b78a4952a076",
          "sha1": "c6ebc42967c4a57e796f2bbd019dad8c11834006",
          "md5": "a625ad80db389852dbf89bc49d6e59a0"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-fabric",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "fabricRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-fabric.jar",
          "url": "PreloadingTricks-3.5.8-fabric.jar",
          "size": 892533,
          "sha512": "e704e8e881c39d8d89ea03a812d0c64dbacfccecaf902154ba28fbc528f6b624cde861295d5051a61454859daecf80c5258f768342a210f54051a7a93197e13e",
          "sha256": "88f5eda30815b2a0ef8164cbbb12d151f2cefc706dd85067ca59b78a4952a076",
          "sha1": "c6ebc42967c4a57e796f2bbd019dad8c11834006",
          "md5": "a625ad80db389852dbf89bc49d6e59a0"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-fabric",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "forgeServiceApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-forge-service.jar",
          "url": "PreloadingTricks-3.5.8-forge-service.jar",
          "size": 944185,
          "sha512": "3d38c58e1b4f041f158a2f40ea3b444271126364b2bd4efaba9b549a05888c5794c013da5bdf0a4a06583df7703227c70906c97e9c9174299a26f1ff7e0a1eca",
          "sha256": "84841a290136e266e2620bff027797d2f7fc49cc2d89c3c07368647ba435cfdd",
          "sha1": "1243f522f1100ffe3e330f2b91ded894d799ce38",
          "md5": "e120e3135b44bec912eceed33bc399cf"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "forgeServiceRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-forge-service.jar",
          "url": "PreloadingTricks-3.5.8-forge-service.jar",
          "size": 944185,
          "sha512": "3d38c58e1b4f041f158a2f40ea3b444271126364b2bd4efaba9b549a05888c5794c013da5bdf0a4a06583df7703227c70906c97e9c9174299a26f1ff7e0a1eca",
          "sha256": "84841a290136e266e2620bff027797d2f7fc49cc2d89c3c07368647ba435cfdd",
          "sha1": "1243f522f1100ffe3e330f2b91ded894d799ce38",
          "md5": "e120e3135b44bec912eceed33bc399cf"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherLegacyApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.6",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.20.6",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-neoforge-modlauncher-legacy.jar",
          "url": "PreloadingTricks-3.5.8-neoforge-modlauncher-legacy.jar",
          "size": 100035,
          "sha512": "54b104622c6245a925cf9c03bdcbd4c864c9454f1da4807dbcc52da9875decc6ebb1cc37f02b63b2efe2ff417e822ab2084bf8af81570cf03c9258fe32884af8",
          "sha256": "1185bd224357429f3ffcff7f0e0468a55fb872c587213c7442ccc70c3288bd04",
          "sha1": "fa83abbfb9d6482dc7ae96e2c156455367670ec4",
          "md5": "493b78afbb813dfee1bcf85145bb8b8d"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher-legacy",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherLegacyRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.6",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.20.6",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-neoforge-modlauncher-legacy.jar",
          "url": "PreloadingTricks-3.5.8-neoforge-modlauncher-legacy.jar",
          "size": 100035,
          "sha512": "54b104622c6245a925cf9c03bdcbd4c864c9454f1da4807dbcc52da9875decc6ebb1cc37f02b63b2efe2ff417e822ab2084bf8af81570cf03c9258fe32884af8",
          "sha256": "1185bd224357429f3ffcff7f0e0468a55fb872c587213c7442ccc70c3288bd04",
          "sha1": "fa83abbfb9d6482dc7ae96e2c156455367670ec4",
          "md5": "493b78afbb813dfee1bcf85145bb8b8d"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher-legacy",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.5.8-neoforge-modlauncher.jar",
          "size": 952852,
          "sha512": "9a96d4675b342c7dcfe7272ff4adbca47a39f8126fcca7b18a5370c269d669dd31b126caa0f7317a283255ea75ddbc24ea0e8f05d598de6eee4a17e8d046544b",
          "sha256": "2b1481f31a85ecba34eda41a6a9308843d6ebf0db873681d68b80ad41476c0d7",
          "sha1": "4ef9f8817c991ea2458db3ad113b19f49d9687b6",
          "md5": "d0a383b29c0df8a0cde634871b579d7b"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.5.8-neoforge-modlauncher.jar",
          "size": 952852,
          "sha512": "9a96d4675b342c7dcfe7272ff4adbca47a39f8126fcca7b18a5370c269d669dd31b126caa0f7317a283255ea75ddbc24ea0e8f05d598de6eee4a17e8d046544b",
          "sha256": "2b1481f31a85ecba34eda41a6a9308843d6ebf0db873681d68b80ad41476c0d7",
          "sha1": "4ef9f8817c991ea2458db3ad113b19f49d9687b6",
          "md5": "d0a383b29c0df8a0cde634871b579d7b"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.5.8-neoforge-fancy-mod-loader.jar",
          "size": 66740,
          "sha512": "040e0184cfab36ef692e4b33be9608fc9f0831da97ea01a4bc9c4608409512bc4bab6ed3c9b39a1df01db979454cd52ad0a6db97aa34f8ac7ff25d202919ffd3",
          "sha256": "b33ca96ba9626909b70b154ccb315902291ddb46a86bb5dff5fc7c73a6ac4f3c",
          "sha1": "2bdc623dbf90afd5dc860e1d240731f78c25cb38",
          "md5": "4d77b98534ebe3206a1030468ed56196"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.17.7-dust.0",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.8-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.5.8-neoforge-fancy-mod-loader.jar",
          "size": 66740,
          "sha512": "040e0184cfab36ef692e4b33be9608fc9f0831da97ea01a4bc9c4608409512bc4bab6ed3c9b39a1df01db979454cd52ad0a6db97aa34f8ac7ff25d202919ffd3",
          "sha256": "b33ca96ba9626909b70b154ccb315902291ddb46a86bb5dff5fc7c73a6ac4f3c",
          "sha1": "2bdc623dbf90afd5dc860e1d240731f78c25cb38",
          "md5": "4d77b98534ebe3206a1030468ed56196"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.8"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "3.5.8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
