{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "java-class-extensions-processor",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-class-extensions-processor-1.0.1.jar",
          "url": "java-class-extensions-processor-1.0.1.jar",
          "size": 12464,
          "sha512": "9d45e647d2e39fe47b693ef2872e08707fc35c77485ca45c0162136a27e873f2454c172adc447902c01e4189621cafcfe3a9953284453210ff7c64a4761e8252",
          "sha256": "9d2435d46b35d3704c5419d09022279a43a173e0202386f4d4dc0148a3e3ec0b",
          "sha1": "760749aeef5b0a0eb5881f5dad125bc7453fa4e8",
          "md5": "ee1e55cb6c28bf950b687ef5d66be489"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "class-extension-annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "java-processor-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-class-extensions-processor-1.0.1.jar",
          "url": "java-class-extensions-processor-1.0.1.jar",
          "size": 12464,
          "sha512": "9d45e647d2e39fe47b693ef2872e08707fc35c77485ca45c0162136a27e873f2454c172adc447902c01e4189621cafcfe3a9953284453210ff7c64a4761e8252",
          "sha256": "9d2435d46b35d3704c5419d09022279a43a173e0202386f4d4dc0148a3e3ec0b",
          "sha1": "760749aeef5b0a0eb5881f5dad125bc7453fa4e8",
          "md5": "ee1e55cb6c28bf950b687ef5d66be489"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-class-extensions-processor-1.0.1-sources.jar",
          "url": "java-class-extensions-processor-1.0.1-sources.jar",
          "size": 2848,
          "sha512": "8b50cf0efaad35b74425ede8ee81e320e68b9856dc61915ad9ff49cfb3ed2253acb7359e8e10ced19ec7b99000d2d961af3217dd75a568f8d745d8c4890742af",
          "sha256": "ed666ecf30e08ef24d05f86c46510e202934fa94cb72860c133b946c3aa309ba",
          "sha1": "67d9e9bb54af7b3309d17eac55cc8c579926dcf3",
          "md5": "1e5c3e8c8f39d845185f0f651622042d"
        }
      ]
    }
  ]
}
