{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "classpath-api-stubs",
    "version": "0.1.12-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "classpath-api-stubs-0.1.12-dust.0.jar",
          "url": "classpath-api-stubs-0.1.12-dust.0.jar",
          "size": 93917,
          "sha512": "e46f3e533a3942d49b9c7d32541f36dbc18266a61a022c59f8c96e651c7a386f6b7c37214d65f892ed3a9f801b07b2bb62b9f5cadcd3cdad226ce2ab617805da",
          "sha256": "aa342cf93f4af351fe83d78576d1283bc75ef18c612bc2012f68d6184668e75b",
          "sha1": "ab03fe2c2d6888d316fa4ccd9570396765f9d890",
          "md5": "a0f73d9c8c90ab3fbc5653a8978acdf5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "classpath-api-stubs-0.1.12-dust.0.jar",
          "url": "classpath-api-stubs-0.1.12-dust.0.jar",
          "size": 93917,
          "sha512": "e46f3e533a3942d49b9c7d32541f36dbc18266a61a022c59f8c96e651c7a386f6b7c37214d65f892ed3a9f801b07b2bb62b9f5cadcd3cdad226ce2ab617805da",
          "sha256": "aa342cf93f4af351fe83d78576d1283bc75ef18c612bc2012f68d6184668e75b",
          "sha1": "ab03fe2c2d6888d316fa4ccd9570396765f9d890",
          "md5": "a0f73d9c8c90ab3fbc5653a8978acdf5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-api-stubs-0.1.12-dust.0-sources.jar",
          "url": "classpath-api-stubs-0.1.12-dust.0-sources.jar",
          "size": 14258,
          "sha512": "a64b62cd61fd8d4620c28ead268f196fd1ac6c912d17252d29585be0da1690da3422b489f9c330263a9cca4a73347eee4e05c43e28f1a4a9cdd89dd940e9e050",
          "sha256": "0f08d62a734435fb208c7c39da2bea625844c88c369f64316d902e515feacd1c",
          "sha1": "c42350b369308fd832b1fdea4a358ade4c6daebc",
          "md5": "a07cef69094e86d152e77afb07c56a6f"
        }
      ]
    }
  ]
}
