{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "java-expect-actual-processor",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-expect-actual-processor-1.0.9.jar",
          "url": "java-expect-actual-processor-1.0.9.jar",
          "size": 16221,
          "sha512": "af3e79727d1fee76168109bce91a75b6c11ae65f8a26b31e84059556b8f17932234663c9a68d5d293774258d921ad319880e303605936e04336b7757793e682a",
          "sha256": "081a6a905dda79cf404864e6235c4d9be70b448485aa8ef1547a0f23ba00c736",
          "sha1": "395038cc111b102edd57482342ec9f9d566d68c4",
          "md5": "3a811c04a41c78fe80fd02c31ce72b03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "java-expect-actual-annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "java-processor-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-expect-actual-processor-1.0.9.jar",
          "url": "java-expect-actual-processor-1.0.9.jar",
          "size": 16221,
          "sha512": "af3e79727d1fee76168109bce91a75b6c11ae65f8a26b31e84059556b8f17932234663c9a68d5d293774258d921ad319880e303605936e04336b7757793e682a",
          "sha256": "081a6a905dda79cf404864e6235c4d9be70b448485aa8ef1547a0f23ba00c736",
          "sha1": "395038cc111b102edd57482342ec9f9d566d68c4",
          "md5": "3a811c04a41c78fe80fd02c31ce72b03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-expect-actual-processor-1.0.9-sources.jar",
          "url": "java-expect-actual-processor-1.0.9-sources.jar",
          "size": 4186,
          "sha512": "88a5291f29869b6fcce9c5fd6f20258a694d6a163194167195d418e13043ad3786b7b66021a7b37a7f297b0cd13ccb36414e45cc8018d863b98b80f000daa016",
          "sha256": "659cca06c67f992ca70db58521c97588287599da4975bfccf0b22aa562733ac7",
          "sha1": "d6e1a660c6b0945762ecd1f830671e6ed9e29e09",
          "md5": "5ff352e2a9a3b5a157e77ee722683ced"
        }
      ]
    }
  ]
}
