{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "java-processor-util",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-processor-util-1.0.0.jar",
          "url": "java-processor-util-1.0.0.jar",
          "size": 14357,
          "sha512": "271a03721569fa80f3625908bd9dc4625d6d6feac3a35a9b89902532cf3ee1a3d60fddaec8ec36600766f781655ff2f4367bcc7a4eeabcdac95ab875001ccd19",
          "sha256": "b7f10525e9b9d75abc9fbea3c7edc58858c5460a247272987ed6dc75c987c7af",
          "sha1": "57d6f5a57cd93c4bc9b38988644c8e161db4a7ef",
          "md5": "e4a69754eda576884843a3d94ffe1312"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-processor-util-1.0.0.jar",
          "url": "java-processor-util-1.0.0.jar",
          "size": 14357,
          "sha512": "271a03721569fa80f3625908bd9dc4625d6d6feac3a35a9b89902532cf3ee1a3d60fddaec8ec36600766f781655ff2f4367bcc7a4eeabcdac95ab875001ccd19",
          "sha256": "b7f10525e9b9d75abc9fbea3c7edc58858c5460a247272987ed6dc75c987c7af",
          "sha1": "57d6f5a57cd93c4bc9b38988644c8e161db4a7ef",
          "md5": "e4a69754eda576884843a3d94ffe1312"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-processor-util-1.0.0-sources.jar",
          "url": "java-processor-util-1.0.0-sources.jar",
          "size": 4803,
          "sha512": "8d9f887365e5c0c2b04a6c3c9071e6e3838030df6a21a325a169289a1a6d9bc09d67aa84f4dc998671c48f09857b7d5e0004a46d42b4d1c5db2920792e093a44",
          "sha256": "54af9e2f9fef4ec30597a83d26784fd85ac27b85e414c629cd866d91cc113bfe",
          "sha1": "f1d653192d5b914926d3861849463649ea0994ce",
          "md5": "473133c5a6907ba0dcd9d83c9305ae1b"
        }
      ]
    },
    {
      "name": "java11SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.version": 11,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-processor-util-1.0.0-java11-sources.jar",
          "url": "java-processor-util-1.0.0-java11-sources.jar",
          "size": 2124,
          "sha512": "3e46600944d71bea2d067ac1106606a3b0d7917495e2c22f1ecbd985bd5e9413415fe9b4ef443b597ade032cb3f9550cfedd6bf4229cfc52aee75789c64afaf1",
          "sha256": "cac742f9caa2e75565ebcdf0aec6a2591a854f43024d661b0b4531d2fe1293e8",
          "sha1": "60a36d6f4701818c7b7c439f105d402b0f080ba1",
          "md5": "499ad6bd16fa58dd79b3e93ca151384e"
        }
      ],
      "capabilities": [
        {
          "group": "net.msrandom",
          "name": "java-processor-util",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "java11ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-processor-util-1.0.0-java11.jar",
          "url": "java-processor-util-1.0.0-java11.jar",
          "size": 6746,
          "sha512": "78903b4acbc4e210163129d8fde3cf17464bbeef28526f2fdcbd23053d2043d8f16362eb50d4c0f06311d2b079e733d56c506a5bdca2b05a24173bee36990056",
          "sha256": "c05c33d17a38ba5bc38d9fc9e5a0f7ad27ffedf0c6513365d7eef2e8b3b077f9",
          "sha1": "be9b62f3e1eb23d31710b4dbdb09a5e00df905b9",
          "md5": "0252ffe032e08135db9d546424e11d51"
        },
        {
          "name": "java-processor-util-1.0.0.jar",
          "url": "java-processor-util-1.0.0.jar",
          "size": 14357,
          "sha512": "271a03721569fa80f3625908bd9dc4625d6d6feac3a35a9b89902532cf3ee1a3d60fddaec8ec36600766f781655ff2f4367bcc7a4eeabcdac95ab875001ccd19",
          "sha256": "b7f10525e9b9d75abc9fbea3c7edc58858c5460a247272987ed6dc75c987c7af",
          "sha1": "57d6f5a57cd93c4bc9b38988644c8e161db4a7ef",
          "md5": "e4a69754eda576884843a3d94ffe1312"
        }
      ],
      "capabilities": [
        {
          "group": "net.msrandom",
          "name": "java-processor-util",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "java11RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "java-processor-util-1.0.0-java11.jar",
          "url": "java-processor-util-1.0.0-java11.jar",
          "size": 6746,
          "sha512": "78903b4acbc4e210163129d8fde3cf17464bbeef28526f2fdcbd23053d2043d8f16362eb50d4c0f06311d2b079e733d56c506a5bdca2b05a24173bee36990056",
          "sha256": "c05c33d17a38ba5bc38d9fc9e5a0f7ad27ffedf0c6513365d7eef2e8b3b077f9",
          "sha1": "be9b62f3e1eb23d31710b4dbdb09a5e00df905b9",
          "md5": "0252ffe032e08135db9d546424e11d51"
        },
        {
          "name": "java-processor-util-1.0.0.jar",
          "url": "java-processor-util-1.0.0.jar",
          "size": 14357,
          "sha512": "271a03721569fa80f3625908bd9dc4625d6d6feac3a35a9b89902532cf3ee1a3d60fddaec8ec36600766f781655ff2f4367bcc7a4eeabcdac95ab875001ccd19",
          "sha256": "b7f10525e9b9d75abc9fbea3c7edc58858c5460a247272987ed6dc75c987c7af",
          "sha1": "57d6f5a57cd93c4bc9b38988644c8e161db4a7ef",
          "md5": "e4a69754eda576884843a3d94ffe1312"
        }
      ],
      "capabilities": [
        {
          "group": "net.msrandom",
          "name": "java-processor-util",
          "version": "1.0.0"
        }
      ]
    }
  ]
}
