{
  "formatVersion": "1.1",
  "component": {
    "group": "settingdust.preloading_tricks",
    "module": "PreloadingTricks",
    "version": "3.5.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-3.5.15.jar",
          "url": "PreloadingTricks-3.5.15.jar",
          "size": 1761132,
          "sha512": "bd4862f8acc61e7b80f2ae4cee826b339f1b7e6e7a3ce1cef4152150693eb7ae9b832da7cda105e8e707de6e4646fb9ea169f6442f706c240f684d39811fb6e0",
          "sha256": "4e8b96f28dc6b9e32af6499b99de0412fd769b30be630ef0950c7cb01592177e",
          "sha1": "b702ba0fb090dee46919bb7554115a04c59bc7f1",
          "md5": "9d9013b958616f0914392afd6917f06b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "PreloadingTricks-3.5.15.jar",
          "url": "PreloadingTricks-3.5.15.jar",
          "size": 1761132,
          "sha512": "bd4862f8acc61e7b80f2ae4cee826b339f1b7e6e7a3ce1cef4152150693eb7ae9b832da7cda105e8e707de6e4646fb9ea169f6442f706c240f684d39811fb6e0",
          "sha256": "4e8b96f28dc6b9e32af6499b99de0412fd769b30be630ef0950c7cb01592177e",
          "sha1": "b702ba0fb090dee46919bb7554115a04c59bc7f1",
          "md5": "9d9013b958616f0914392afd6917f06b"
        }
      ]
    },
    {
      "name": "fabricApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.15-fabric.jar",
          "url": "PreloadingTricks-3.5.15-fabric.jar",
          "size": 836328,
          "sha512": "895867df63297710a7dccdec0aa2a7f9c07dab85d3c4420f631089ac54f1f7f89cea44c830a172f21f1e0791cc6c438aeec458711fcda54b2ede5bc718584dde",
          "sha256": "d0fc8fd75c41c8b362284892bc8788d2d4c1fafc27115f450a1d96aad96e9488",
          "sha1": "d17672afcae78d1d985a99ee531987f49a570070",
          "md5": "e532ddabcd3d45d95cf62d0066d2bf8f"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-fabric",
          "version": "3.5.15"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.15"
        }
      ]
    },
    {
      "name": "fabricRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.15-fabric.jar",
          "url": "PreloadingTricks-3.5.15-fabric.jar",
          "size": 836328,
          "sha512": "895867df63297710a7dccdec0aa2a7f9c07dab85d3c4420f631089ac54f1f7f89cea44c830a172f21f1e0791cc6c438aeec458711fcda54b2ede5bc718584dde",
          "sha256": "d0fc8fd75c41c8b362284892bc8788d2d4c1fafc27115f450a1d96aad96e9488",
          "sha1": "d17672afcae78d1d985a99ee531987f49a570070",
          "md5": "e532ddabcd3d45d95cf62d0066d2bf8f"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-fabric",
          "version": "3.5.15"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.15"
        }
      ]
    },
    {
      "name": "forgeServiceApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.15-forge-service.jar",
          "url": "PreloadingTricks-3.5.15-forge-service.jar",
          "size": 897143,
          "sha512": "3447230f6c92eac2eaad1900e9db18e23dd6d25da4cf18d2040d8ffe7e89bce0625e1660086d87c7015010638b5228be745ee92d192e48b5506e9ad5d1bddb5b",
          "sha256": "7e9316eb527827ddaa2d4a8c3487b4a691440294a4b4a5919f6111606f88f303",
          "sha1": "36cfa3bda5a92979948c0e453676a014a99186fb",
          "md5": "1684bd677efe6ee541f9844e130a26c9"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "3.5.15"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.15"
        }
      ]
    },
    {
      "name": "forgeServiceRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.15-forge-service.jar",
          "url": "PreloadingTricks-3.5.15-forge-service.jar",
          "size": 897143,
          "sha512": "3447230f6c92eac2eaad1900e9db18e23dd6d25da4cf18d2040d8ffe7e89bce0625e1660086d87c7015010638b5228be745ee92d192e48b5506e9ad5d1bddb5b",
          "sha256": "7e9316eb527827ddaa2d4a8c3487b4a691440294a4b4a5919f6111606f88f303",
          "sha1": "36cfa3bda5a92979948c0e453676a014a99186fb",
          "md5": "1684bd677efe6ee541f9844e130a26c9"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "3.5.15"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.15"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.15-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.5.15-neoforge-modlauncher.jar",
          "size": 896287,
          "sha512": "abb0c8e8c3ed0020d3cc701eba163b9b95950b88416af49d77ad42da4c954156c50cfe35ed5b4ff44b10d2430fb16dc0cfac3e3d9cb3389a161cba8429865a76",
          "sha256": "251026c6187cedb8cf8bdd8303cff2fc8ea1203ccef63bf5ac66e03c8a471b0e",
          "sha1": "fab6b6ec0dce4d0b876ac40d8effab8e582b74a3",
          "md5": "7eab905bb378623b96f2f255664fb038"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.15"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "3.5.15"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.15-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-3.5.15-neoforge-modlauncher.jar",
          "size": 896287,
          "sha512": "abb0c8e8c3ed0020d3cc701eba163b9b95950b88416af49d77ad42da4c954156c50cfe35ed5b4ff44b10d2430fb16dc0cfac3e3d9cb3389a161cba8429865a76",
          "sha256": "251026c6187cedb8cf8bdd8303cff2fc8ea1203ccef63bf5ac66e03c8a471b0e",
          "sha1": "fab6b6ec0dce4d0b876ac40d8effab8e582b74a3",
          "md5": "7eab905bb378623b96f2f255664fb038"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.15"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "3.5.15"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.15-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.5.15-neoforge-fancy-mod-loader.jar",
          "size": 69138,
          "sha512": "3fc976019ec9c50b37748b3337ba2ff6c4c73ea521bfa5d56009a62276809bf1cae21ab3cbf9ef0b9c5be6cced6dd5f81322d074aba1101a44a12a6223d91faf",
          "sha256": "679f5fd202a2a2301d838a69a5b25463cea92637f37770f679462744cf5d4a6c",
          "sha1": "f1c35e44a8cb4e0c948b3379a8d2eb1fd58c56c5",
          "md5": "7592059d78046bfd7dd7be38c0e73dd9"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "3.5.15"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.15"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "earth.terrarium.cloche.version": "0.18.11-dust.8",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "mixinstranslator",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-3.5.15-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-3.5.15-neoforge-fancy-mod-loader.jar",
          "size": 69138,
          "sha512": "3fc976019ec9c50b37748b3337ba2ff6c4c73ea521bfa5d56009a62276809bf1cae21ab3cbf9ef0b9c5be6cced6dd5f81322d074aba1101a44a12a6223d91faf",
          "sha256": "679f5fd202a2a2301d838a69a5b25463cea92637f37770f679462744cf5d4a6c",
          "sha1": "f1c35e44a8cb4e0c948b3379a8d2eb1fd58c56c5",
          "md5": "7592059d78046bfd7dd7be38c0e73dd9"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "3.5.15"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "3.5.15"
        }
      ]
    }
  ]
}
