{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-forge",
    "version": "0.9.2-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.9.2-dust.0.jar",
          "url": "minecraft-codev-forge-0.9.2-dust.0.jar",
          "size": 311923,
          "sha512": "4c31399fa4af2d3d2d623aef6ee3ac698377bffb328429faac6f0a16831ec1fa97231e00ea44b405d889fca843b5ce55acfbe22aa904525021b1003a42e9f3b6",
          "sha256": "9dd06c3f8240afe66941996d5f339fa973678abf2bfc937917a8029fd6fefb6d",
          "sha1": "fae230a0756ff7d0080e2fe47ab49e3a3e79a474",
          "md5": "94806d8d39585286ecdbd38ae01c1c6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core-serialization",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-cli",
          "version": {
            "requires": "13.0.3"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3-dust.3"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.2-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.7.2-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-forge-0.9.2-dust.0.jar",
          "url": "minecraft-codev-forge-0.9.2-dust.0.jar",
          "size": 311923,
          "sha512": "4c31399fa4af2d3d2d623aef6ee3ac698377bffb328429faac6f0a16831ec1fa97231e00ea44b405d889fca843b5ce55acfbe22aa904525021b1003a42e9f3b6",
          "sha256": "9dd06c3f8240afe66941996d5f339fa973678abf2bfc937917a8029fd6fefb6d",
          "sha1": "fae230a0756ff7d0080e2fe47ab49e3a3e79a474",
          "md5": "94806d8d39585286ecdbd38ae01c1c6b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.9.2-dust.0-sources.jar",
          "url": "minecraft-codev-forge-0.9.2-dust.0-sources.jar",
          "size": 36965,
          "sha512": "ce21f23f431038de7cabe986ea34042cc19df45c940611fd5107bf387b5b9b1276951adcb27baf4c107deb49fc8fd410ae02ab896a95f3b5d23d20b10498caad",
          "sha256": "af781fd15bae153c3f8f2a87a2a67ebf93941d034b140db6620e5881d8c7ffaf",
          "sha1": "a16fd309fadea526b64ee011810a43c5b39ab3f8",
          "md5": "0b3cd891b766bcc77febf3f9c700a516"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.9.2-dust.0-javadoc.jar",
          "url": "minecraft-codev-forge-0.9.2-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
