{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-includes",
    "version": "0.6.5-dust.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-includes-0.6.5-dust.1.jar",
          "url": "minecraft-codev-includes-0.6.5-dust.1.jar",
          "size": 24767,
          "sha512": "406ecdbddd2874c71e0e2f95f0ec8d4991165ef05a43683f51dc6118f86e004076618aa723343d6b6362b2dd345b9066e4a9faace9ecdfb08a08378c1ef221e9",
          "sha256": "d861a1e87851df421211da0040ff95c12d18d3dc24a5320026fff243cf57e860",
          "sha1": "24accdedcf850604b0ea2fd888f25ad068b21478",
          "md5": "cb35cedbfaa5febe4021cb5f4af0067b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.7.2-dust.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-includes-0.6.5-dust.1.jar",
          "url": "minecraft-codev-includes-0.6.5-dust.1.jar",
          "size": 24767,
          "sha512": "406ecdbddd2874c71e0e2f95f0ec8d4991165ef05a43683f51dc6118f86e004076618aa723343d6b6362b2dd345b9066e4a9faace9ecdfb08a08378c1ef221e9",
          "sha256": "d861a1e87851df421211da0040ff95c12d18d3dc24a5320026fff243cf57e860",
          "sha1": "24accdedcf850604b0ea2fd888f25ad068b21478",
          "md5": "cb35cedbfaa5febe4021cb5f4af0067b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-includes-0.6.5-dust.1-sources.jar",
          "url": "minecraft-codev-includes-0.6.5-dust.1-sources.jar",
          "size": 5588,
          "sha512": "e547229e37eaf201143967a14245b3aaddbafec11910a194d46a32772461f987aa39b4b1c994f4ea2d6368be88c7ea1afb9a6ac0df23c28fa571b9c854806085",
          "sha256": "860d18c970abb9d092869affa68b0b8f87b164ab72f55ef6932525d1bfc77ca1",
          "sha1": "1f9bc96e9895525fde79895f3fa9ab9d191c92db",
          "md5": "ca1b0b814766e81416329d60f3dc1485"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-includes-0.6.5-dust.1-javadoc.jar",
          "url": "minecraft-codev-includes-0.6.5-dust.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
