{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-fabric",
    "version": "0.7.2-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-fabric-0.7.2-dust.0.jar",
          "url": "minecraft-codev-fabric-0.7.2-dust.0.jar",
          "size": 132205,
          "sha512": "8a5d422c15830504fae0fe06b57d9b1695aa94a0ae35dbe4ab1d31f81fd79ea42a0f2cc4798553da59d5a57016bbaebfbe881682e843e8d0bdf669194e1fc1f1",
          "sha256": "8612a90f077d39bf9fff6f133eadf1282450246f6794b8613b4c8048bc41e2a1",
          "sha1": "314bdba6e0dcaa33590953d2bff7d546ca808821",
          "md5": "af02c492f2c38f33ef8c2b4dc98eacaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3-dust.3"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.2-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.7.2-dust.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-fabric-0.7.2-dust.0.jar",
          "url": "minecraft-codev-fabric-0.7.2-dust.0.jar",
          "size": 132205,
          "sha512": "8a5d422c15830504fae0fe06b57d9b1695aa94a0ae35dbe4ab1d31f81fd79ea42a0f2cc4798553da59d5a57016bbaebfbe881682e843e8d0bdf669194e1fc1f1",
          "sha256": "8612a90f077d39bf9fff6f133eadf1282450246f6794b8613b4c8048bc41e2a1",
          "sha1": "314bdba6e0dcaa33590953d2bff7d546ca808821",
          "md5": "af02c492f2c38f33ef8c2b4dc98eacaa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-fabric-0.7.2-dust.0-sources.jar",
          "url": "minecraft-codev-fabric-0.7.2-dust.0-sources.jar",
          "size": 17126,
          "sha512": "ba43a3d40493ceecdf4709420b93a207037390beedfaa2b912a1526a4d4147685d10b81a36ceddc2995c7c69fa2a06ca08a8acf676d65a197704674de9d96143",
          "sha256": "834fad54241f2931ea1fa5777deb8830f507f4550d737ef201290efd1a20831a",
          "sha1": "1fcb263e5856cb767ce62fdae16ad60a8ac10474",
          "md5": "72608b98fca0c3d16641e95068caca09"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-fabric-0.7.2-dust.0-javadoc.jar",
          "url": "minecraft-codev-fabric-0.7.2-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
