{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-access-widener",
    "version": "0.6.3-dust.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0-beta.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.3.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.3.jar",
          "size": 88411,
          "sha512": "a520ec13d4732011c390535c3e156e998ef30d225e56f867e7dfa38c4e0f4a2e33986674bd2c6e0aec4550e9e43b029e3b1484e287b76880389bba38df0b5a6a",
          "sha256": "d8df76bf9295bbc53fdd34e28abc78faaaf7e32339b19f7f15cafe1c5ffec5e3",
          "sha1": "9ecdda5e265f76e6081b91c12948b8f8603904e6",
          "md5": "edfa9ee199199c38c3484d262f0a587a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0-beta.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.3.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.3.jar",
          "size": 88411,
          "sha512": "a520ec13d4732011c390535c3e156e998ef30d225e56f867e7dfa38c4e0f4a2e33986674bd2c6e0aec4550e9e43b029e3b1484e287b76880389bba38df0b5a6a",
          "sha256": "d8df76bf9295bbc53fdd34e28abc78faaaf7e32339b19f7f15cafe1c5ffec5e3",
          "sha1": "9ecdda5e265f76e6081b91c12948b8f8603904e6",
          "md5": "edfa9ee199199c38c3484d262f0a587a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.3-sources.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.3-sources.jar",
          "size": 8361,
          "sha512": "6652729b4694e37aabdb225fad2492b96435af3adf7bfa8a1d9dd02c19c633ceafe42db2ccdd179429dc2c91ce5b3d289c09b333e540d6b66289bced8c6ec3f5",
          "sha256": "abfaa664d425917a6832e9ebd2b2730533a0ee96f34b45f19b210ddf68cec242",
          "sha1": "9c4ea4f5b6e8570e9636cd7c8fb774fcf62fd56a",
          "md5": "aaba44c3040b08d373c5b8bc8a0f8bad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.3-javadoc.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
