{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-access-widener",
    "version": "0.6.3-dust.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0-beta.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.3.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.3.jar",
          "size": 88433,
          "sha512": "4a2b33f867eb6bb91b4aca422cfc8f6001121b9c9acf11e83f0b901bb32ed5fdb2202e74318614a0be00141e6ce024ec3538aa0ebeade16f5e378690929e2264",
          "sha256": "16c12327999806db5b07b5087e24df2f9b6629f2994d376cdf9596d2d492bdf3",
          "sha1": "0a49b36bee6bfbb45aff0e23b59a38b01d0cf7e7",
          "md5": "9fa836ed3b076caaadcec661b867eb00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.7.2-dust.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0-beta.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.3.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.3.jar",
          "size": 88433,
          "sha512": "4a2b33f867eb6bb91b4aca422cfc8f6001121b9c9acf11e83f0b901bb32ed5fdb2202e74318614a0be00141e6ce024ec3538aa0ebeade16f5e378690929e2264",
          "sha256": "16c12327999806db5b07b5087e24df2f9b6629f2994d376cdf9596d2d492bdf3",
          "sha1": "0a49b36bee6bfbb45aff0e23b59a38b01d0cf7e7",
          "md5": "9fa836ed3b076caaadcec661b867eb00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.3-sources.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.3-sources.jar",
          "size": 8361,
          "sha512": "6652729b4694e37aabdb225fad2492b96435af3adf7bfa8a1d9dd02c19c633ceafe42db2ccdd179429dc2c91ce5b3d289c09b333e540d6b66289bced8c6ec3f5",
          "sha256": "abfaa664d425917a6832e9ebd2b2730533a0ee96f34b45f19b210ddf68cec242",
          "sha1": "9c4ea4f5b6e8570e9636cd7c8fb774fcf62fd56a",
          "md5": "aaba44c3040b08d373c5b8bc8a0f8bad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.3-javadoc.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
