{
  "formatVersion": "1.1",
  "component": {
    "group": "settingdust.preloading_tricks",
    "module": "PreloadingTricks",
    "version": "9bca6ba",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.modLoader": "common",
        "earth.terrarium.cloche.side": "Common",
        "io.github.mcgradleconventions.distribution": "common",
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba.jar",
          "url": "PreloadingTricks-9bca6ba.jar",
          "size": 1556674,
          "sha512": "dd16552388a5bcdfd175cc0cdb1fe5022bf8ba13aabc7673892a166dc4063301fbeb741e783e1e3e2ba24b70cf6e4879f99c3654feb4fbf60f1727afb96ded4f",
          "sha256": "5c00e7a95c7773a6b7c1780f137cb4803b2f18e6783766c0b1b9a567dd953023",
          "sha1": "c2b1cad347126cf8253978c49025df169f639b6d",
          "md5": "f2c90359bdaec1af9b740a3f37770b26"
        }
      ]
    },
    {
      "name": "versionFabric1201ApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-version-fabric-1.20.1.jar",
          "url": "PreloadingTricks-9bca6ba-version-fabric-1.20.1.jar",
          "size": 603749,
          "sha512": "7d41c8eb749754ad4ee9b7bc3b6e5423f9d0cccefcc6e1f6a5effc7698373597efb85a7a0992d5576fff82e9761f101e1d2bc142b7d7153dbc4bc4192cfdce08",
          "sha256": "53ae2cfb1c366aaf5029fdb1ce95e528b8fa57b4df7f8359d1a85861107d81e6",
          "sha1": "aabedcf9a748b08416d3a4ea28636e656a8733d4",
          "md5": "f498f8c5f19a00319dbc176da842e2bd"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-fabric-1.20.1",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionFabric1201RuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "de.florianmichael",
          "module": "AsmFabricLoader",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-version-fabric-1.20.1.jar",
          "url": "PreloadingTricks-9bca6ba-version-fabric-1.20.1.jar",
          "size": 603749,
          "sha512": "7d41c8eb749754ad4ee9b7bc3b6e5423f9d0cccefcc6e1f6a5effc7698373597efb85a7a0992d5576fff82e9761f101e1d2bc142b7d7153dbc4bc4192cfdce08",
          "sha256": "53ae2cfb1c366aaf5029fdb1ce95e528b8fa57b4df7f8359d1a85861107d81e6",
          "sha1": "aabedcf9a748b08416d3a4ea28636e656a8733d4",
          "md5": "f498f8c5f19a00319dbc176da842e2bd"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-fabric-1.20.1",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionFabric121ApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-fabric-1.21",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionFabric121RuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "fabric",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "fabric",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "de.florianmichael",
          "module": "AsmFabricLoader",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-fabric-1.21",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "forgeServiceApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-forge-service.jar",
          "url": "PreloadingTricks-9bca6ba-forge-service.jar",
          "size": 919814,
          "sha512": "6402ea25a0c2fc4753e00fac0c94db96c2c951dca290ffbc2370dcdc3896f9fd12c9ebfcb55c84e4b40b85b3b00f3286f820564e7fbb4c7a275b24c54f925e87",
          "sha256": "98efb1ce9cf18037e21bd7a0381d0c685bb3c4189b7047c603a2c95ea8192dc9",
          "sha1": "9accd43a12cd35d5a2f7aaa7e8abb009a9f34299",
          "md5": "129739c942061dc724c496012ebca426"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "forgeServiceRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-forge-service.jar",
          "url": "PreloadingTricks-9bca6ba-forge-service.jar",
          "size": 919814,
          "sha512": "6402ea25a0c2fc4753e00fac0c94db96c2c951dca290ffbc2370dcdc3896f9fd12c9ebfcb55c84e4b40b85b3b00f3286f820564e7fbb4c7a275b24c54f925e87",
          "sha256": "98efb1ce9cf18037e21bd7a0381d0c685bb3c4189b7047c603a2c95ea8192dc9",
          "sha1": "9accd43a12cd35d5a2f7aaa7e8abb009a9f34299",
          "md5": "129739c942061dc724c496012ebca426"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-forge-service",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionForge1201ApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-forge-1.20.1",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionForge1201RuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.1",
        "earth.terrarium.cloche.modLoader": "forge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "forge",
        "io.github.mcgradleconventions.version": "1.20.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "settingdust.preloading_tricks",
          "module": "PreloadingTricks",
          "version": {
            "requires": "9bca6ba"
          },
          "requestedCapabilities": [
            {
              "group": "settingdust.preloading_tricks",
              "name": "PreloadingTricks-forge-service"
            }
          ]
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-forge-1.20.1",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherLegacyApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.6",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.20.6",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-neoforge-modlauncher-legacy.jar",
          "url": "PreloadingTricks-9bca6ba-neoforge-modlauncher-legacy.jar",
          "size": 96049,
          "sha512": "4823b0eb50d560091bf8aacd11e91518e9810819a369d478216403061811cd57152828fed40a5a2763f770a3639b7f76a76f1519331dd8416a0cca9381630dbf",
          "sha256": "f1e3b85e796f07fdb94950e776e6166381431633973ba66e1aff39d1ae5007f9",
          "sha1": "62ffe866be9fb0503c73eab9fb89446f78508be1",
          "md5": "a3d414451070e72b0f1fdad7f8ae8f55"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher-legacy",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherLegacyRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.6",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.20.6",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-neoforge-modlauncher-legacy.jar",
          "url": "PreloadingTricks-9bca6ba-neoforge-modlauncher-legacy.jar",
          "size": 96049,
          "sha512": "4823b0eb50d560091bf8aacd11e91518e9810819a369d478216403061811cd57152828fed40a5a2763f770a3639b7f76a76f1519331dd8416a0cca9381630dbf",
          "sha256": "f1e3b85e796f07fdb94950e776e6166381431633973ba66e1aff39d1ae5007f9",
          "sha1": "62ffe866be9fb0503c73eab9fb89446f78508be1",
          "md5": "a3d414451070e72b0f1fdad7f8ae8f55"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher-legacy",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-9bca6ba-neoforge-modlauncher.jar",
          "size": 929369,
          "sha512": "26aabdc832fb666530a70734de21ad86460a272576b22a20be0259190a523df5a114d8b89839d584ba9d9b7bc9eab98d7455f87549f9c44da06b2c1d57fef6a9",
          "sha256": "eca328ebf9cec08f513307e7442f7248a3788db3ef2201af149cc9d214a52be4",
          "sha1": "0fd42ea71ca14bf1e53b2109365ab03c79ff0836",
          "md5": "a09bb018440b8443a49cb9d0f30ae468"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "neoforgeModlauncherRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-neoforge-modlauncher.jar",
          "url": "PreloadingTricks-9bca6ba-neoforge-modlauncher.jar",
          "size": 929369,
          "sha512": "26aabdc832fb666530a70734de21ad86460a272576b22a20be0259190a523df5a114d8b89839d584ba9d9b7bc9eab98d7455f87549f9c44da06b2c1d57fef6a9",
          "sha256": "eca328ebf9cec08f513307e7442f7248a3788db3ef2201af149cc9d214a52be4",
          "sha1": "0fd42ea71ca14bf1e53b2109365ab03c79ff0836",
          "md5": "a09bb018440b8443a49cb9d0f30ae468"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-modlauncher",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-9bca6ba-neoforge-fancy-mod-loader.jar",
          "size": 62991,
          "sha512": "712a2e29620a568387d466c83d69935e3287b0f66762adb203b145c52e0c60c12c190ef12bdccbdb517005ad04f52eba3f82b23fa7143b0797e6cb42e9897f5d",
          "sha256": "eaad306431f4a0c07a5c89ffac2b7cba6b9a34ebf3dc8e924fc7b32296cf62c6",
          "sha1": "7991a1af44615e57fa561f8ec04ff86830569d3d",
          "md5": "2a008e7636232e0cade56e202c6d3cd1"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "neoforgeFancyModLoaderRuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.lenni0451",
          "module": "Reflect",
          "version": {
            "requires": "1.6.1-SNAPSHOT"
          }
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "core",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.lenni0451.classtransform",
          "module": "additionalclassprovider",
          "version": {
            "requires": "1.15.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            },
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "PreloadingTricks-9bca6ba-neoforge-fancy-mod-loader.jar",
          "url": "PreloadingTricks-9bca6ba-neoforge-fancy-mod-loader.jar",
          "size": 62991,
          "sha512": "712a2e29620a568387d466c83d69935e3287b0f66762adb203b145c52e0c60c12c190ef12bdccbdb517005ad04f52eba3f82b23fa7143b0797e6cb42e9897f5d",
          "sha256": "eaad306431f4a0c07a5c89ffac2b7cba6b9a34ebf3dc8e924fc7b32296cf62c6",
          "sha1": "7991a1af44615e57fa561f8ec04ff86830569d3d",
          "md5": "2a008e7636232e0cade56e202c6d3cd1"
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-neoforge-fancy-mod-loader",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionNeoforge1206ApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.6",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.20.6",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-neoforge-1.20.6",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionNeoforge1206RuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.20.6",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.20.6",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-neoforge-1.20.6",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionNeoforge1211ApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-neoforge-1.21.1",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionNeoforge1211RuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.1",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.1",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-neoforge-1.21.1",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionNeoforge12110ApiElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-neoforge-1.21.10",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "versionNeoforge12110RuntimeElements",
      "attributes": {
        "earth.terrarium.cloche.data": false,
        "earth.terrarium.cloche.minecraftVersion": "1.21.10",
        "earth.terrarium.cloche.modLoader": "neoforge",
        "earth.terrarium.cloche.side": "Client",
        "io.github.mcgradleconventions.distribution": "client",
        "io.github.mcgradleconventions.loader": "neoforge",
        "io.github.mcgradleconventions.version": "1.21.10",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "settingdust.preloading_tricks",
          "module": "PreloadingTricks",
          "version": {
            "requires": "9bca6ba"
          },
          "requestedCapabilities": [
            {
              "group": "settingdust.preloading_tricks",
              "name": "PreloadingTricks-neoforge-fancy-mod-loader"
            }
          ]
        }
      ],
      "capabilities": [
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks",
          "version": "9bca6ba"
        },
        {
          "group": "settingdust.preloading_tricks",
          "name": "PreloadingTricks-version-neoforge-1.21.10",
          "version": "9bca6ba"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
