{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-access-widener",
    "version": "0.6.3-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.0.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.0.jar",
          "size": 78975,
          "sha512": "ddaafc12fefd924d5ade45cc0f853d50b2a04a8703bf7e077afc5aa9417b54176d711278670a6f2a5216dc6875cab7911d769a58085a20d5693040f1e0f36230",
          "sha256": "dcbeeedfe8ec261c78814d12333787d616a5056aaf3be2bdffbeae1e2f65ae4c",
          "sha1": "a5d0383db2db9b514d85d82b2c345e89c46c14e3",
          "md5": "a52e009cd8e477bda6e178783c81f24e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "at",
          "version": {
            "requires": "0.1.0-rc1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.0.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.0.jar",
          "size": 78975,
          "sha512": "ddaafc12fefd924d5ade45cc0f853d50b2a04a8703bf7e077afc5aa9417b54176d711278670a6f2a5216dc6875cab7911d769a58085a20d5693040f1e0f36230",
          "sha256": "dcbeeedfe8ec261c78814d12333787d616a5056aaf3be2bdffbeae1e2f65ae4c",
          "sha1": "a5d0383db2db9b514d85d82b2c345e89c46c14e3",
          "md5": "a52e009cd8e477bda6e178783c81f24e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.0-sources.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.0-sources.jar",
          "size": 8033,
          "sha512": "804885bc70bffea3f86c1e898b600c43454794da39f2725304057b989080ba851b6793cd18d9b15b445f64d31f9fd1076949feed750c9f6af89640fc30e94e04",
          "sha256": "1a1027baaeeccb87f0d16519b6b9edf9c3332d4a7f49dfafc5947cb87d7c68e6",
          "sha1": "1dc408ca7262b24e30e8ff7c118d174ade9e1844",
          "md5": "96ae47f0fef29b4652ab4260c395c277"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-access-widener-0.6.3-dust.0-javadoc.jar",
          "url": "minecraft-codev-access-widener-0.6.3-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
