{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-core",
    "version": "0.7.2-dust.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-core-0.7.2-dust.0.jar",
          "url": "minecraft-codev-core-0.7.2-dust.0.jar",
          "size": 311958,
          "sha512": "34da3a949e8a011b48de207ccb43a29fd28f1d84491001ed719031a3056d8fdc3dc0392132b6ced009a40aa7dc71b539e768f18d2aba7b00536798c261a6d126",
          "sha256": "f2d7fc3318e6133d0e547909823a5b36e8cb9e25b72e63becf66d8bef1368e3f",
          "sha1": "b8a6e39c7a9bc18d060ccde89f37d78761d89818",
          "md5": "3f76032643afd0dd4d6715a2d2770b07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "side-annotations",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-core-0.7.2-dust.0.jar",
          "url": "minecraft-codev-core-0.7.2-dust.0.jar",
          "size": 311958,
          "sha512": "34da3a949e8a011b48de207ccb43a29fd28f1d84491001ed719031a3056d8fdc3dc0392132b6ced009a40aa7dc71b539e768f18d2aba7b00536798c261a6d126",
          "sha256": "f2d7fc3318e6133d0e547909823a5b36e8cb9e25b72e63becf66d8bef1368e3f",
          "sha1": "b8a6e39c7a9bc18d060ccde89f37d78761d89818",
          "md5": "3f76032643afd0dd4d6715a2d2770b07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-core-0.7.2-dust.0-sources.jar",
          "url": "minecraft-codev-core-0.7.2-dust.0-sources.jar",
          "size": 34958,
          "sha512": "8b92f998db6de699fce09082674d0685482921dd0cdb7ad889e5da023acb4445d9395822dc3e0b31a805042803e9c5439fc5742a7e40bc32a82477e9759f30ae",
          "sha256": "632eb4d9e53be87e8393d7926e0c48529a57b9f0d6a6d9482a5488b79c9f214a",
          "sha1": "a58e69ce24db6495e644cffb493d5a2d9b2ca8cf",
          "md5": "a6857efc4bd921496788ef22f3f1c2c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-core-0.7.2-dust.0-javadoc.jar",
          "url": "minecraft-codev-core-0.7.2-dust.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
