{
  "formatVersion": "1.1",
  "component": {
    "group": "earth.terrarium",
    "module": "cloche",
    "version": "0.18.11-dust.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cloche-0.18.11-dust.14.jar",
          "url": "cloche-0.18.11-dust.14.jar",
          "size": 1136401,
          "sha512": "cfef21dda4926e4aba14fc9c66fa1deae8d1a3d62a6ade101d303619504765e34c8c2108e09ef47db36929a294fde8b6c27de6816e04e6562ef2f59c69c9f944",
          "sha256": "455e4a90fb5b781da996a99ee5bdad838d22c2e854cdf3477f1930612538517c",
          "sha1": "f3305f64059c95f99d028950226ddb1d0cd02405",
          "md5": "c2d9217a3c8e2bea7a92d4240051b9ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-forge",
          "version": {
            "requires": "0.8.4-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-fabric",
          "version": {
            "requires": "0.7.0-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.8-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3-dust.3"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.1-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-decompiler",
          "version": {
            "requires": "0.6.0-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extensions-gradle-plugin",
          "version": {
            "requires": "1.0.12"
          }
        },
        {
          "group": "net.msrandom",
          "module": "jvm-virtual-source-sets",
          "version": {
            "requires": "1.3.6-dust.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "classpath-api-stubs",
          "version": {
            "requires": "0.1.12-dust.3"
          }
        },
        {
          "group": "net.peanuuutz.tomlkt",
          "module": "tomlkt",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.18.11-dust.14.jar",
          "url": "cloche-0.18.11-dust.14.jar",
          "size": 1136401,
          "sha512": "cfef21dda4926e4aba14fc9c66fa1deae8d1a3d62a6ade101d303619504765e34c8c2108e09ef47db36929a294fde8b6c27de6816e04e6562ef2f59c69c9f944",
          "sha256": "455e4a90fb5b781da996a99ee5bdad838d22c2e854cdf3477f1930612538517c",
          "sha1": "f3305f64059c95f99d028950226ddb1d0cd02405",
          "md5": "c2d9217a3c8e2bea7a92d4240051b9ef"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.18.11-dust.14-javadoc.jar",
          "url": "cloche-0.18.11-dust.14-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.18.11-dust.14-sources.jar",
          "url": "cloche-0.18.11-dust.14-sources.jar",
          "size": 86222,
          "sha512": "ab4d8b630e7865acbee80fd8dc387bce297c751a1d3006730d96415538ab0b2752cf71c36832b315d306841cd9a08d414affa040ecdc0f3528901c64dd7e1be9",
          "sha256": "2af64ff71243115d41e6b6540402aab39781cf98d7e9c1cce0db71eaa25358f7",
          "sha1": "d92cea953f324b015c1cce7de5a7e51a8c05208b",
          "md5": "b7255bb97c4af8e591d2c16b2c6095cf"
        }
      ]
    }
  ]
}
