{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-forge",
    "version": "0.8.1-dust.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.1-dust.1.jar",
          "url": "minecraft-codev-forge-0.8.1-dust.1.jar",
          "size": 307139,
          "sha512": "ebd24c7ecc16e4e16d3e128a411145738a72e03bb6917da5541539019c2c054064d46459f864664e8319d7e3faa0ee194f614a04b452a4843d118e2b2fcd7997",
          "sha256": "abaf14a278de398e40969010fbff9967e2f7f56157cb9dafdcf50021b0eb17f7",
          "sha1": "59839b7ab68b793173458d5d431ef8ddd843f7c7",
          "md5": "103e822004e3b838c5c7202e525ad8b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core-serialization",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "net.neoforged.accesstransformers",
          "module": "at-cli",
          "version": {
            "requires": "13.0.3"
          }
        },
        {
          "group": "org.cadixdev",
          "module": "lorenz",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.8"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.1-dust.1.jar",
          "url": "minecraft-codev-forge-0.8.1-dust.1.jar",
          "size": 307139,
          "sha512": "ebd24c7ecc16e4e16d3e128a411145738a72e03bb6917da5541539019c2c054064d46459f864664e8319d7e3faa0ee194f614a04b452a4843d118e2b2fcd7997",
          "sha256": "abaf14a278de398e40969010fbff9967e2f7f56157cb9dafdcf50021b0eb17f7",
          "sha1": "59839b7ab68b793173458d5d431ef8ddd843f7c7",
          "md5": "103e822004e3b838c5c7202e525ad8b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.1-dust.1-sources.jar",
          "url": "minecraft-codev-forge-0.8.1-dust.1-sources.jar",
          "size": 36711,
          "sha512": "5cb922400fe47648a8c18399e74e40d764b5d4c1f8092ea3e7f75690282d6027419df6f7d8d2c0dc1238b446f82568f3c0dccaf71c392c3dd4c2b03eaee14311",
          "sha256": "322a39d21b29332b26e66626ad11c3000f016e495d75315ff0f5d424c5c2345e",
          "sha1": "cf6ba1c100dceb31d20531a3ebc840013fe81e35",
          "md5": "45d3d53bd8ab8195c8371196dd7bb366"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-forge-0.8.1-dust.1-javadoc.jar",
          "url": "minecraft-codev-forge-0.8.1-dust.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
