{
  "formatVersion": "1.1",
  "component": {
    "group": "earth.terrarium",
    "module": "cloche",
    "version": "0.18.10-dust.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cloche-0.18.10-dust.2.jar",
          "url": "cloche-0.18.10-dust.2.jar",
          "size": 1143206,
          "sha512": "9b33b8976a55058e4e135c2e1db417aad2e9315b6420e714c9b12604c9d1c931a743eeb43b8d01781cb1bd9d08d74596b0d2ef4e754dc30fc37270f2db9bdd3e",
          "sha256": "d30c563103d7bfe66dc00a9c82c065df2b5e845df8666d03270926f852f7cecc",
          "sha1": "04fffe000cff68daa8c79f3adeee8e246024dd40",
          "md5": "eab3e674866c216baf7ff3030e513210"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.9-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-forge",
          "version": {
            "requires": "0.8.3-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-fabric",
          "version": {
            "requires": "0.7.0-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.6.1-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.8-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.6.3-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.7.1-dust.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-decompiler",
          "version": {
            "requires": "0.6.0-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.5-dust.1"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extensions-gradle-plugin",
          "version": {
            "requires": "1.0.12"
          }
        },
        {
          "group": "net.msrandom",
          "module": "jvm-virtual-source-sets",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "net.msrandom",
          "module": "classpath-api-stubs",
          "version": {
            "requires": "0.1.12-dust.0"
          }
        },
        {
          "group": "net.peanuuutz.tomlkt",
          "module": "tomlkt",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.18.10-dust.2.jar",
          "url": "cloche-0.18.10-dust.2.jar",
          "size": 1143206,
          "sha512": "9b33b8976a55058e4e135c2e1db417aad2e9315b6420e714c9b12604c9d1c931a743eeb43b8d01781cb1bd9d08d74596b0d2ef4e754dc30fc37270f2db9bdd3e",
          "sha256": "d30c563103d7bfe66dc00a9c82c065df2b5e845df8666d03270926f852f7cecc",
          "sha1": "04fffe000cff68daa8c79f3adeee8e246024dd40",
          "md5": "eab3e674866c216baf7ff3030e513210"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.18.10-dust.2-javadoc.jar",
          "url": "cloche-0.18.10-dust.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.18.10-dust.2-sources.jar",
          "url": "cloche-0.18.10-dust.2-sources.jar",
          "size": 86829,
          "sha512": "c686538603dba0e01906ac2765be6ca3761d8f37f01dc77c87f8e145c35643ce1a66472150f53eaedd202ec1b61cbb2febe3a66276e6d7e35e8321ba1a1d89e5",
          "sha256": "c2be610226657b136d8b3219ab94d482f551d106bdecfc8cd4ae71abcaca0610",
          "sha1": "fb9ef65ac70dad36969e31a2f0cf2add6a0cfccb",
          "md5": "5037630bcf30d4bb41b58126b43ef34c"
        }
      ]
    }
  ]
}
